"use strict";
// Generated by python -m dailynews.exterior_tags; edit the Python vocabulary.
(() => {
  const rules = [
  {
    "tag": "冷却",
    "pattern": "冷却|放熱|熱マネジメント|热管理|(?<![A-Za-z0-9])(?:cooling|thermal management|heat dissipation)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "3Dプリンター",
    "pattern": "3Dプリンタ[ー]?|3D印刷|積層造形|付加製造|增材制造|3D打印|(?<![A-Za-z0-9])(?:3d[ -]print(?:ing|ed|ers?)|additive manufacturing)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "CN/CE",
    "pattern": "カーボンニュートラル|サーキュラーエコノミー|脱炭素|資源循環|循環経済|再生材|リサイクル|再利用|碳中和|循环经济|回收|(?<![A-Za-z0-9])(?:CN/CE|carbon[ -]neutral(?:ity)?|circular economy|recycl\\w*|reuse|decarbon\\w*)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "NV",
    "pattern": "騒音|振動|静粛|遮音|吸音|噪声|振动|(?<![A-Za-z0-9])(?:NVH?|noise|vibration|acoustic\\w*)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "低コスト化",
    "pattern": "低コスト|コスト(?:低減|削減)|原価低減|降本|(?<![A-Za-z0-9])(?:cost[ -](?:reduction|saving|savings|effective)|low[ -]cost|reduc\\w* costs?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "バックドア",
    "pattern": "バックドア|テールゲート|リフトゲート|尾门|(?<![A-Za-z0-9])(?:tailgates?|liftgates?|rear hatch|back doors?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "フェンダー",
    "pattern": "フェンダー|翼子板|(?<![A-Za-z0-9])(?:fenders?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "ドア",
    "pattern": "ドア|车门|(?<![A-Za-z0-9])(?:doors?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "ルーフ",
    "pattern": "ルーフ|車頂|车顶|(?<![A-Za-z0-9])(?:roofs?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "リアスポイラー",
    "pattern": "リアスポイラー|リヤスポイラー|後部スポイラー|尾翼|扰流板|(?<![A-Za-z0-9])(?:rear spoilers?|rear wings?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "ピラー",
    "pattern": "ピラー|立柱|(?<![A-Za-z0-9])(?:pillars?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "フード",
    "pattern": "フード|ボンネット|发动机罩|(?<![A-Za-z0-9])(?:hoods?|bonnets?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "型内塗装",
    "pattern": "型内塗装|金型内塗装|インモールド(?:塗装|コーティング)|模内涂装|(?<![A-Za-z0-9])(?:in[ -]mou?ld coat(?:ing)?|IMC)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "ホットスタンプ",
    "pattern": "ホットスタンプ|熱間プレス|加飾箔転写|热冲压|烫印|(?<![A-Za-z0-9])(?:hot[ -]stamp(?:ing|ed)?|press harden(?:ing|ed)|foil transfer)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "インクジェット",
    "pattern": "インクジェット|喷墨|(?<![A-Za-z0-9])(?:ink[ -]?jet)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "フィルム",
    "pattern": "フィルム|薄膜|(?<![A-Za-z0-9])(?:films?|foils?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "印刷",
    "pattern": "印刷|プリント|(?<![A-Za-z0-9])(?:print(?:ing|ed)?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "メッキ",
    "pattern": "メッキ|めっき|電鍍|电镀|クロム|(?<![A-Za-z0-9])(?:plating|electroplat\\w*|chrom(?:e|ium))(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "レーザー",
    "pattern": "レーザー?|激光(?!雷达)|(?<![A-Za-z0-9])(?:lasers?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "ミリ波",
    "pattern": "ミリ波|毫米波|(?<![A-Za-z0-9])(?:milli(?:meter|metre)[ -]waves?|mmwave)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "Lidar",
    "pattern": "ライダー|ライダ[ー]?センサ|光検出測距|激光雷达|(?<![A-Za-z0-9])(?:LiDAR)(?![A-Za-z0-9])",
    "aliases": [
      "LiDAR"
    ]
  },
  {
    "tag": "カメラ",
    "pattern": "カメラ|摄像头|(?<![A-Za-z0-9])(?:cameras?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "ソナー",
    "pattern": "ソナー|超音波|超声波|(?<![A-Za-z0-9])(?:sonar|ultrasonic\\w*)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "フロントエンドモジュール",
    "pattern": "フロントエンドモジュール|フロントモジュール|前端模块|(?<![A-Za-z0-9])(?:front[ -]end modules?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "軽量",
    "pattern": "軽量|轻量|(?<![A-Za-z0-9])(?:light[ -]?weight|weight reduction)(?![A-Za-z0-9])",
    "aliases": [
      "軽量化"
    ]
  },
  {
    "tag": "アブソーバー",
    "pattern": "アブソーバ[ー]?|衝撃吸収|吸能|(?<![A-Za-z0-9])(?:absorbers?|energy absorb\\w*)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "シームレス",
    "pattern": "シームレス|継ぎ目(?:の)?ない|无缝|(?<![A-Za-z0-9])(?:seamless)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "樹脂化",
    "pattern": "樹脂化|樹脂代替|樹脂置換|塑料替代|(?<![A-Za-z0-9])(?:metal replacement|plastic replacement|replac\\w* metal with (?:plastic|polymer))(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "鉄との接合",
    "pattern": "鉄との接合|異材接合|(?:鉄|鋼)[^。.!?\\n]{0,24}(?:樹脂|接合)|樹脂[^。.!?\\n]{0,24}(?:鉄|鋼)|钢塑|异种材料连接|(?<![A-Za-z0-9])(?:(?:polymer|plastic)[ -]metal join\\w*|steel[ -]polymer|hybrid join\\w*|dissimilar material join\\w*)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "塗装",
    "pattern": "塗装|塗料|コーティング|涂装|涂层|(?<![A-Za-z0-9])(?:paint(?:s|ed|ing)?|coat(?:ing|ings|ed))(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "歩行者保護",
    "pattern": "歩行者保護|歩行者安全|行人保护|(?<![A-Za-z0-9])(?:pedestrian (?:protection|safety))(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "軽衝突",
    "pattern": "軽衝突|低速衝突|低速碰撞|(?<![A-Za-z0-9])(?:low[ -]speed (?:impact|collision|crash))(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "法規",
    "pattern": "法規|規制|安全基準|法规|(?<![A-Za-z0-9])(?:regulations?|legislation|regulatory|FMVSS|UNECE)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "アセス",
    "pattern": "アセス|安全性能評価|安全评价|(?<![A-Za-z0-9])(?:NCAP|crash assessment)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "自動運転",
    "pattern": "自動運転|自动驾驶|(?<![A-Za-z0-9])(?:autonomous driving|self[ -]driving|automated driving)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "車両骨格",
    "pattern": "車両骨格|車体骨格|ホワイトボディ|白车身|(?<![A-Za-z0-9])(?:body[ -]in[ -]white|BIW|vehicle structure|body structure)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "ADAS",
    "pattern": "先進運転支援|先進運転者支援|驾驶辅助|(?<![A-Za-z0-9])(?:ADAS|advanced driver assistance)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "走行安定",
    "pattern": "走行安定|操縦安定|行驶稳定|(?<![A-Za-z0-9])(?:driving stability|vehicle stability|handling stability)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "Cd値",
    "pattern": "Cd値|空気抵抗係数|抗力係数|风阻系数|(?<![A-Za-z0-9])(?:Cd(?=\\s*[=:]?\\s*0?\\.\\d)|drag coefficient)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "グリル",
    "pattern": "グリル|格栅|フロントパネル|(?<![A-Za-z0-9])(?:grilles?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "バンパー",
    "pattern": "バンパー|保险杠|(?<![A-Za-z0-9])(?:bumpers?|fascia)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "加飾",
    "pattern": "加飾|塗装|メッキ|めっき|クロム|エンブレム|(?<![A-Za-z0-9])(?:decorat\\w*|emblems?|chrome|plating)(?![A-Za-z0-9])",
    "aliases": [
      "外装加飾"
    ]
  },
  {
    "tag": "照明・発光",
    "pattern": "照明|発光|ライト|ランプ|前大灯|尾灯|(?<![A-Za-z0-9])(?:lighting|illumin\\w*|LED|headlights?|headlamps?|taillights?|taillamps?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "センサー対応",
    "pattern": "センサー|レーダー|レドーム|ライダー|ミリ波|カメラ|ソナー|透過|透波|(?<![A-Za-z0-9])(?:sensors?|radars?|radomes?|LiDAR|ADAS|cameras?|sonar|ultrasonic\\w*)(?![A-Za-z0-9])",
    "aliases": [
      "センサー透過"
    ]
  },
  {
    "tag": "空力",
    "pattern": "空力|エアロ|空気抵抗|シャッター|スポイラー|ディフューザ|空气动力|(?<![A-Za-z0-9])(?:aerodynamic\\w*|shutters?|spoilers?|drag coefficient)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "新素材",
    "pattern": "樹脂|材料|成形|新素材|素材|树脂|(?<![A-Za-z0-9])(?:polymers?|resins?|materials?|mou?lding)(?![A-Za-z0-9])",
    "aliases": [
      "材料"
    ]
  },
  {
    "tag": "サステナビリティ",
    "pattern": "リサイクル|再生材|バイオ|脱炭素|資源循環|循環経済|(?<![A-Za-z0-9])(?:recycl\\w*|sustainab\\w*|bio[ -]based|circular economy)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "サプライチェーン",
    "pattern": "工場|生産拠点|サプライチェーン|(?<![A-Za-z0-9])(?:factor(?:y|ies)|plants?|supply chain)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "エンブレム",
    "pattern": "エンブレム|车标|(?<![A-Za-z0-9])(?:emblems?)(?![A-Za-z0-9])",
    "aliases": []
  },
  {
    "tag": "シール",
    "pattern": "ウェザーストリップ|ウエザーストリップ|シール材|密封条|(?<![A-Za-z0-9])(?:weather[ -]?strips?|weatherstripping|body seal(?:ing|s)?)(?![A-Za-z0-9])",
    "aliases": []
  }
];
  const patterns = rules.map(rule => new RegExp(rule.pattern, "i"));
  const canonical = tag => rules.find(rule => rule.tag === tag || rule.aliases.includes(tag))?.tag || tag;
  function derive(item) {
    // Stored tags and application ideas cannot become evidence for new tags.
    const text = [item?.title, item?.desc, item?.summary].filter(Boolean).join(" ").normalize("NFKC");
    return rules.filter((rule, index) => patterns[index].test(text)).map(rule => rule.tag);
  }
  window.DailyNewsExteriorTags = {rules, derive, canonical,
    matches: (item, tag) => (item.tags || []).includes(canonical(tag))};
})();
