"""Publish a dated ECB reference-rate snapshot for the static news cards."""

import argparse
import datetime as dt
import json
import math
import os
from pathlib import Path
import urllib.request
import xml.etree.ElementTree as ET


SOURCE_URL = "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml"
OUTPUT = Path(__file__).resolve().parent / "exchange_rates.js"
PREFIX = "window.DAILYNEWS_EXCHANGE_RATES = "


def parse_rates(xml, today=None):
    today = today or dt.date.today()
    root = ET.fromstring(xml)
    day = next(node for node in root.iter() if "time" in node.attrib)
    date = dt.date.fromisoformat(day.attrib["time"])
    if date > today or (today - date).days > 10:
        raise ValueError(f"Unexpected ECB rate date: {date}")
    euro_rates = {"EUR": 1.0}
    for node in day:
        code = node.get("currency")
        rate = float(node.get("rate", "nan"))
        if not code or not math.isfinite(rate) or rate <= 0:
            raise ValueError("Invalid ECB rate")
        euro_rates[code] = rate
    if not {"JPY", "USD", "EUR", "CNY", "INR", "GBP"} <= euro_rates.keys():
        raise ValueError("Missing required currencies")
    return {
        "date": date.isoformat(),
        "checkedOn": today.isoformat(),
        "source": "European Central Bank",
        "sourceUrl": SOURCE_URL,
        "base": "JPY",
        "rates": {code: round(euro_rates["JPY"] / rate, 10)
                  for code, rate in sorted(euro_rates.items())},
    }


def read_snapshot(path):
    text = path.read_text(encoding="utf-8")
    return json.loads(text.split(PREFIX, 1)[1].strip().removesuffix(";"))


def update_rates(path=OUTPUT, force=False):
    today = dt.date.today()
    cached = None
    try:
        cached = read_snapshot(path)
        if not force and cached.get("checkedOn") == today.isoformat():
            print(f"[FX] Already checked today; reference date={cached['date']}")
            return
    except (OSError, ValueError, IndexError):
        pass
    try:
        request = urllib.request.Request(SOURCE_URL, headers={"User-Agent": "DailyNews/1.0"})
        proxies = urllib.request.getproxies()
        if not (proxies.get("http") or proxies.get("https")) and os.name == "nt":
            # Unrelated *_PROXY variables can suppress urllib's registry fallback.
            proxies = urllib.request.getproxies_registry()
        opener = urllib.request.build_opener(urllib.request.ProxyHandler(proxies))
        with opener.open(request, timeout=20) as response:
            snapshot = parse_rates(response.read(256_000), today)
        if cached and snapshot["date"] < cached["date"]:
            raise ValueError("ECB returned an older snapshot")
        temporary = path.with_suffix(".tmp")
        temporary.write_text(
            "// JPY per one unit of foreign currency; generated by update_exchange_rates.py.\n"
            + PREFIX + json.dumps(snapshot, ensure_ascii=True, indent=2) + ";\n",
            encoding="utf-8",
        )
        os.replace(temporary, path)
        print(f"[FX] Updated {len(snapshot['rates'])} currencies; reference date={snapshot['date']}")
    except Exception as exc:
        # Preserve the last valid snapshot; the UI shows its date and hides stale rates.
        print(f"[FX][WARN] {type(exc).__name__}; kept reference date={cached.get('date') if cached else 'none'}")
        if not cached:
            raise RuntimeError("No exchange-rate snapshot is available") from exc


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    update_rates(force=args.force)
