window.LOADED_NEWS_DATA = [
    // 2026-09-14 (google検索からExcel sheet2_llm_targets)
    {
        id: "jp1",
        title: "レクサスLS改良でリアLマークがLEXUSバラ文字へ変更",
        desc: "トヨタは2026年9月10日、フラッグシップセダン「LS」の一部改良モデルを発売した。リア中央のエンブレムが従来の「L」マークから「LEXUS」のバラ文字に変更され、SNSではカッコいいという好評と威厳が失われたという惜しむ声が交錯している。",
        url: "https://news.yahoo.co.jp/articles/16a0805370a2422175e6e9cb042f8e45a9ede24d?source=rss",
        source: "VAGUE",
        date: "2026-09-14",
        tags: ["エンブレム"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        sourceExcerpt: "リア中央のブランドロゴが、「L」をかたどった従来仕様のエンブレムから、「LEXUS」の文字を一文字ずつ配置した“バラ文字エンブレム”に変更されています。",
        interiorScore: 85,
        interiorReason: "リアエンブレムのデザイン変更（Lマークからバラ文字へ）という具体的な外装コンポーネントの技術的・意匠的特徴が記事の中心であり、対象範囲に合致する。",
        imageInterior: false,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-10456791-vague-000-1-view.jpg",
        note: ""
    },
    {
        id: "us1",
        title: "BMW X5にカーボン製グリルとアラミド製ディフューザーを追加",
        desc: "BMWは2027年型X5向けに、カーボンファイバー製のグリルインサートやフロントスプリッター、アラミド素材のスポーティなディフューザーなど、M Performance Partsによる外装アクセサリーをラインナップした。",
        url: "https://www.carscoops.com/2026/09/2027-bmw-x5-m-performace-parts/",
        source: "CarScoops",
        date: "2026-09-14",
        tags: ["グリル", "材料"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        sourceExcerpt: "Starting up front, customers can get carbon fiber grille inserts as well as a carbon fiber front splitter.",
        interiorScore: 85,
        interiorReason: "カーボンファイバー製のグリルインサートとスプリッター、アラミド製ディフューザーという外装部品の素材と設計が記載されている。",
        imageInterior: false,
        country: "us",
        img: "https://www.carscoops.com/wp-content/uploads/2026/09/2027-BMW-X5-M-Performace-Pa-1024x578.jpg",
        note: ""
    },
    // 2026-09-15 (google検索からExcel sheet2_llm_targets)
    {
        id: "jp2",
        title: "ケンスタイルEIK、NDロードスターのフロント加飾事例を紹介",
        desc: "Auto Messe Webは2016年取材の事例として、ケンスタイル「EIK」のNDロードスターデモカーを紹介した。純正の雰囲気を生かすフロントハーフスポイラーに、リアはフジツボのオーソライズRMと専用ディフューザーを組み合わせる。マフラー本体はステンレス製で、青色のチタンテールを左右4本出しとした構成。",
        url: "https://news.yahoo.co.jp/articles/5003ae23c7e440ec545e3adff5659fdfccc8ca1e?source=rss",
        source: "Auto Messe Web",
        date: "2026-09-15",
        tags: ["過去事例", "外装加飾"],

        edition: "exterior", productScore: 65, exteriorScore: 65,
        sourceExcerpt: "ケンスタイルのエアロブランド「EIK」が選んだ答えは、オリジナルエアロをフロントハーフスポイラー1点に絞り、リアはフジツボ製チタンマフラーと専用ディフューザーのセットに任せる潔い構成だ。",
        interiorScore: 65,
        interiorReason: "NDロードスター用のフロントハーフスポイラーという具体的な外装エアロパーツの採用と、純正雰囲気を損なわないデザイン意図が記載されている。",
        imageInterior: false,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-00010008-amweb-000-1-view.jpg",
        note: "2016年取材の事例紹介。掲載日と製品発表日は異なります。"
    },
    {
        id: "us2",
        title: "次期AMG GT Black Series開発車、フェンダー上部の可動フラップを報道",
        desc: "CarScoopsは、ニュルブルクリンク近郊で撮影された次期AMG GT Black Seriesの開発車を紹介した。記事はフロントフェンダー上部の可動フラップ、ドア外板に沿って空気を流す側面ベント、スワンネック支柱の大型リアウイングを挙げる。フラップの開閉による圧力解放や空気抵抗低減は、記事筆者の推測として述べられている。",
        url: "https://www.carscoops.com/2026/09/amg-gt-black-series-looks-like-its-smashed-the-ring-record-before-its-even-hit-the-track/",
        source: "CarScoops",
        date: "2026-09-15",
        tags: ["開発車", "空力"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        sourceExcerpt: "sets of active flaps mounted in the top of each front fender",
        interiorScore: 85,
        interiorReason: "開発車のフロントフェンダー上部の可動フラップや側面ベントなど、具体的な外装コンポーネントが報道されている。用途の一部は記者の推測であり、性能は未確認。",
        imageInterior: false,
        country: "us",
        img: "https://www.carscoops.com/wp-content/uploads/2026/09/AMG-Black-scoop-Sep2614111-1024x576.jpg",
        note: "開発車の写真に基づく報道。量産仕様・性能の確定情報ではありません。"
    },
    // 2026-09-15 (google検索からExcel sheet2_llm_targets)
    {
        id: "jp3",
        title: "シエンタ、黒色ドアミラーと新ボディ色へ仕様整理",
        desc: "carview!が2026年8月のシエンタの一部改良を振り返った。全グレードのドアミラーをブラック加飾へ統一し、新色クリアベージュメタリックを追加。従来のベージュ、スカーレットメタリック、ツートーン色は廃止されたと紹介している。",
        url: "https://news.yahoo.co.jp/articles/6178ce0a6d838340cac6bbddc8be5bc302b0afa9?source=rss",
        source: "carview!",
        date: "2026-09-15",
        tags: ["外装加飾"],

        edition: "exterior", productScore: 72, exteriorScore: 72,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "さらに全グレードにおいて、これまでボディ同色だったドアミラーがブラック加飾に統一された。",
        interiorScore: 72,
        interiorReason: "トヨタシエンタの改良において、全グレードでドアミラーがブラック加飾に統一され、ボディカラーラインナップも見直された。外装パーツの意匠変更と色指定の整理は、エクス",
        imageInterior: false,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-00010011-carv-000-1-view.jpg",
        note: ""
    },
    {
        id: "us3",
        title: "AMG GLC 53改良開発車、グリルと星型灯火の変更を報道",
        desc: "Carscoopsが迷彩をまとったAMG GLC 53クーペのテスト車を紹介した。記事は新グリルと前後の星型の灯火意匠への変更を予測している。量産仕様の確定発表ではなく、開発車の写真に基づく報道。",
        url: "https://www.carscoops.com/2026/09/amgs-glc-is-getting-a-new-look-but-not-the-cle-646s-v8/",
        source: "CarScoops",
        date: "2026-09-15",
        tags: ["グリル"],

        edition: "exterior", productScore: 75, exteriorScore: 75,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "The visual changes will be subtle, focusing on a new grille and",
        sourceExcerptEnd: "cluster and angled console tablet found in the current car.",
        interiorScore: 75,
        interiorReason: "AMG GLCのマイナーチェンジにおいて、新グリルと星型DRLという具体的な外装部品のデザイン変更が言及されており、プレミアムSUVセグメントにおけるフロントマ",
        imageInterior: false,
        country: "us",
        img: "https://www.carscoops.com/wp-content/uploads/2026/09/AMG-GLC-lead-Sep152611-1024x576.jpg",
        note: ""
    },
    {
        id: "eu1",
        title: "JLR、ステランティスとディフェンダーのピックアップを検討と報道",
        desc: "AutocarはTimes報道を引用し、JLRがステランティスとの提携で北米向けディフェンダーのピックアップを検討していると伝えた。米国生産や採用する車台は未確定で、JLRは報道へのコメントを控えている。",
        url: "https://www.autocar.co.uk/car-news/new-cars/report-jlr-collaborating-stellantis-defender-pick",
        source: "AUTOCAR UK",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 75, exteriorScore: 75,
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "JLR is considering building a Defender pick-up as part of its new alliance with Stellantis, according to a report in The Times.",
        interiorScore: 75,
        interiorReason: "JLRとStellantisの提携によるDefenderピックアップ開発検討は、北米市場でのOEM戦略やプラットフォーム活用に関する具体的なシグナルであり、外装",
        imageInterior: false,
        country: "eu",
        img: "https://images.cdn.autocar.co.uk/sites/autocar.co.uk/files/styles/car_review_image_190/public/images/car-reviews/first-drives/legacy/land_rover_defender_crew_1_1.jpg?itok=qyvuFzaN",
        note: ""
    },
    {
        id: "eu2",
        title: "アウディRS Q5とみられる開発車、角形グリルと縦長吸気口",
        desc: "Auto Expressは、RS Q5とみられる開発車の小型フェンダー拡張部、角張ったグリル、その両側の縦長で細い吸気口、後部の大型楕円形排気口を報じた。撮影車はスポーツバック型で、量産仕様・出力・発売時期は未確定。",
        url: "https://www.autoexpress.co.uk/audi/q5/370434/first-ever-audi-rs-q5-spied-massive-phev-power-and-snarling-style",
        source: "Auto Express",
        date: "2026-09-15",
        tags: ["グリル"],

        edition: "exterior", productScore: 82, exteriorScore: 82,
        contentCategory: "trend", trendTopic: "competitor",
        sourceExcerpt: "This is obvious with the prototype’s grille, which has a squarer shape, flanked by two tall and narrow outer intakes.",
        interiorScore: 82,
        interiorReason: "アウディRS Q5のプロトタイプにおいて、角張ったグリル形状や外側インテーク、フェンダー延長など具体的なエクステリアデザイン変更が報告されており、競合他社の最新",
        imageInterior: false,
        country: "eu",
        img: "https://media.autoexpress.co.uk/image/private/s--DXyJF5fN--/t_rss_image_w_845/v1789463067/autoexpress/2026/09/New%20Audi%20RS%20Q5%20Sportback%20001.jpg",
        note: ""
    },
    {
        id: "cn1",
        title: "Voyah Dream 9、格納式発光オーナメントを採用",
        desc: "東風傘下のVoyahは旗艦MPV「Dream 9」を9月22日に発売すると発表した。縦型クロームグリルと格納式の発光フードオーナメント、Huawei Xpixel投影ヘッドライトを備え、ツートーンの外装を用意する。",
        url: "https://carnewschina.com/2026/09/15/voyah-dream-9-flagship-mpv-with-701-km-range-set-to-launch-on-september-22/",
        source: "CarNewsChina - All",
        date: "2026-09-15",
        tags: ["グリル", "照明・発光"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "It is equipped with Huawei Xpixel smart projection headlights.",
        interiorScore: 85,
        interiorReason: "「Dragon Scale」グリル、リトラクタブル式イルミネーションエンブレム、Huawei Xpixelヘッドライトなど、外装コンポーネントの具体的な設計と機",
        imageInterior: false,
        country: "cn",
        img: "https://carnewschina.com/wp-content/uploads/2026/09/e59bbee78987-110-e1789454207654.png",
        note: ""
    },
    {
        id: "cn2",
        title: "フリーランダー8、中国で9月19日納車開始へ",
        desc: "奇瑞ジャガー・ランドローバーは「フリーランダー8」の中国納車を9月19日に始めると発表した。Concept 97を由来とする箱型の外観に、閉じたフロントマスクと長方形ヘッドライトを組み合わせ、ルーフ上にLiDARを配置する。",
        url: "https://carnewschina.com/2026/09/15/freelander-8-china-deliveries-to-begin-september-19/",
        source: "CarNewsChina - All",
        date: "2026-09-15",
        tags: ["照明・発光"],

        edition: "exterior", productScore: 74, exteriorScore: 74,
        contentCategory: "trend", trendTopic: "competitor",
        sourceExcerpt: "The front fascia features a closed-off design paired with rectangular headlights.",
        interiorScore: 74,
        interiorReason: "中国市場での発売開始と12時間5,000台の受注実績という具体的な市場データに加え、フロントマスクのクローズドデザインやLiDAR搭載など外装設計に関する記述が",
        imageInterior: false,
        country: "cn",
        img: "https://carnewschina.com/wp-content/uploads/2026/09/e59bbee78987-109-e1789435232593_webhook_1500x900_q85_1789435476.jpg",
        note: ""
    },
    {
        id: "in1",
        title: "マルチ・スズキ ワゴンR改良型の開発車、グリルやバンパーを変更",
        desc: "Autocar IndiaがワゴンRの開発車を報道。ヘッドランプの細部やグリル、前部の吸気口に変更が見られ、後部バンパーの反射板は横型から縦型になっている。市販仕様は記事時点で未確定。",
        url: "https://www.autocarindia.com/car-news/maruti-suzuki-wagon-r-facelift-spied-testing-440755",
        source: "Autocar India - All",
        date: "2026-09-15",
        tags: ["グリル", "バンパー", "照明・発光"],

        edition: "exterior", productScore: 62, exteriorScore: 62,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "The test mule was spotted with new detailing for the halogen headlamps,",
        sourceExcerptEnd: "finish for the bumper and redesigned air inlets lower down.",
        interiorScore: 62,
        interiorReason: "ワゴンRのフェイスリフトにおいて、グリル形状の変更やヘッドランプ意匠の更新、バンパーおよびエアインレットのデザイン変更といった具体的な外装パーツの計画が示唆され",
        imageInterior: false,
        country: "in",
        img: "https://asset.autocarindia.com/static/news/images/20260915_114450_cc6f12d9.jpg",
        note: ""
    },
    {
        id: "in2",
        title: "フェラーリ296 GT Modificata、新スプリッターと大型固定翼",
        desc: "フェラーリはサーキット専用の296 GT Modificataを発表。前部スプリッターと冷却用吸気口を改め、後部ウィングは中央支柱や5mmのガーニーフラップなどを更新した。GT3 Evoを基にした顧客向け限定車。",
        url: "https://www.autocarindia.com/car-news/ferrari-296-gt-modificata-debuts-as-supercars-most-extreme-version-yet-440754",
        source: "Autocar India - All",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "The exhaust tips are also of a completely new design for the",
        sourceExcerptEnd: "is barely unchanged from the one on the GT3 Evo.",
        interiorScore: 85,
        interiorReason: "フェラーリ296 GT Modificataの空力コンポーネント（フロントスポイラー、リアウィング、Gurneyフラップ、エアインテーク）の詳細な設計と機能に関",
        imageInterior: false,
        country: "in",
        img: "https://asset.autocarindia.com/static/news/images/20260915_111105_dd098842.jpg",
        note: ""
    },
    {
        id: "in3",
        title: "BMW i5 LWBをインドで試乗、発光グリルとM専用バンパー",
        desc: "RushLaneがインド仕様のBMW i5 LWBを試乗。発光キドニーグリル、M専用前後バンパー、窓枠とCピラーのサテン仕上げ、20インチMエアロホイールを紹介した。価格は796万ルピーから（現地車両価格）。",
        url: "https://www.rushlane.com/bmw-i5-lwb-review-spacious-fast-and-surprisingly-fun-12555908.html",
        source: "RushLane",
        date: "2026-09-15",
        tags: ["グリル", "バンパー", "照明・発光"],

        edition: "exterior", productScore: 74, exteriorScore: 74,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "I liked Hofmeister kink and 5 labelling on C Pillar, BMW kidney",
        sourceExcerptEnd: "even the 20-inch M aero wheels (245-section front, 275-section rear).",
        interiorScore: 74,
        interiorReason: "BMW i5 LWBのレビュー記事であり、Illuminated Kidney Grille（発光キドニーグリル）、M専用フロント/リアバンパー、アルミサテン仕",
        imageInterior: true,
        country: "in",
        img: "https://www.rushlane.com/wp-content/uploads/2026/09/bmw-i5-lwb-review-cover.jpg",
        note: ""
    },
    {
        id: "in4",
        title: "Wrangler JL-2A、民生用CJ-2Aを着想源に外装配色を変更",
        desc: "1945年の民生用ウィリスCJ-2Aに着想を得た装備パッケージ。オレンジ系のホイールと牽引フック、7スロットグリルの濃灰色アクセントを採用する。記事では追加価格4,995米ドル、10月受注開始としている。",
        url: "https://www.rushlane.com/jeep-wrangler-pays-tribute-to-iconic-willys-jeep-from-world-war-ii-era-12555851.html",
        source: "RushLane",
        date: "2026-09-15",
        tags: ["グリル"],

        edition: "exterior", productScore: 74, exteriorScore: 74,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "These include a Dark Metallic Grey accent for the iconic seven slot grille.",
        interiorScore: 74,
        interiorReason: "Wrangler JL-2A特別パッケージにおいて、7スロットグリルのダークメタリックグレーアクセントやJooseカラーホイール、オレンジ色トウフックなど外装コ",
        imageInterior: true,
        country: "in",
        img: "https://www.rushlane.com/wp-content/uploads/2026/09/jeep-wrangler-willys-edition-launch-price-4.jpg",
        note: ""
    },
    {
        id: "in5",
        title: "Denza D9・Z9 GTのインド導入観測、グリルや後部意匠を紹介",
        desc: "RushLaneはDenza D9とZ9 GTのインド導入見通しを報じた。既存車の意匠として、D9の縦桟グリル、Z9 GTの前後LED照明と大型リアディフューザーを紹介。導入時期やインド仕様は未確定。",
        url: "https://www.rushlane.com/byd-denza-d9-luxury-mpv-and-z9-gt-1156-bhp-fastback-india-launch-soon-12555798.html",
        source: "RushLane",
        date: "2026-09-15",
        tags: ["グリル", "照明・発光"],

        edition: "exterior", productScore: 70, exteriorScore: 70,
        contentCategory: "trend", trendTopic: "competitor",
        sourceExcerpt: "Front fascia has a large and imposing grille with vertical slats, while rear is flat, with interesting LED tail light signature.",
        interiorScore: 70,
        interiorReason: "BYD Denza D9とZ9 GTのインド市場投入に関する記事で、フロントグリル形状やLEDライトシグネチャー、リアディフューザーなど外装デザイン要素が具体的",
        imageInterior: true,
        country: "in",
        img: "https://www.rushlane.com/wp-content/uploads/2026/09/byd-denza-d9-and-z9-gt-india.jpg",
        note: ""
    },
    {
        id: "in6",
        title: "次期タタNexon開発車、Aピラーやリアスポイラー変更の可能性",
        desc: "IndiaCarNewsは次期Nexonの試験車を紹介。写真からAピラー、後部ドア、スポイラーに小変更があると推測する。新テールランプやバンパーの採用は予想段階で、市販仕様は未確定。",
        url: "https://www.indiacarnews.com/news/new-rs-8-lakh-tata-suv-coming-in-2027-with-new-platform-69005/",
        source: "IndiaCarNews",
        date: "2026-09-15",
        tags: ["バンパー", "照明・発光"],

        edition: "exterior", productScore: 74, exteriorScore: 74,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "The SUV might also receive newly-designed LED taillamps, revised tailgate and bumper.",
        interiorScore: 74,
        interiorReason: "次期型NexonのAピラー、リアスポイラー、LEDテールランプおよびバンパーの変更が具体的に言及されており、外装デザイン計画に有用な情報を含む。",
        imageInterior: false,
        country: "in",
        img: "https://www.indiacarnews.com/wp-content/uploads/2026/06/New-Tata-Nexon-2027-Launch.webp",
        note: ""
    },
    {
        id: "in7",
        title: "ヒョンデの新SUV開発車、H字型ライトとグリルの意匠を報道",
        desc: "IndiaCarNewsはBayonとする開発車の角形ホイールアーチ、スラットグリル、H字型LEDデイライトを紹介。価格約100万ルピーから、数週間内の発売はいずれも同媒体の見通しで、公式仕様は未公表。",
        url: "https://www.indiacarnews.com/news/new-rs-10-lakh-hyundai-suv-launching-soon-victoris-rival-69002/",
        source: "IndiaCarNews",
        date: "2026-09-15",
        tags: ["グリル", "照明・発光"],

        edition: "exterior", productScore: 75, exteriorScore: 75,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "Upfront, the SUV will feature a slatted grille, H-styled top-mounted LED DRLs, LED headlamps in trapezoidal housing and a sporty bumper.",
        interiorScore: 75,
        interiorReason: "ヒュンダイ新SUVベイオンの外装デザイン（スラットグリル、H型LED DRL、トラペゾイド形状ヘッドランプ、スポーティバンパー）が具体的に記載されており、競合モ",
        imageInterior: false,
        country: "in",
        img: "https://www.indiacarnews.com/wp-content/uploads/2026/09/Untitled-Design-13.webp",
        note: ""
    },
    {
        id: "jp4",
        title: "新型CX-5の受注動向、販売店では上級Lが好評",
        desc: "carview!は、5月発売の新型CX-5が6月21日時点で国内受注1万台を超えたと紹介した。取材した販売店の声として、室内空間の広さへの評価や上級グレード「L」の人気を報道。受注実績と販売店への取材から、ミッドサイズSUVの需要を振り返る記事。",
        url: "https://news.yahoo.co.jp/articles/8d8604452771a7888ed61e760510c7ff5d59f4f9?source=rss",
        source: "carview!",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 72, exteriorScore: 72,
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "2026年5月21日に新型CX-5が発売され、約1か月後の6月21日時点で、国内受注台数が1万台を超え、月間販売計画2000台の5倍以上に達しています。",
        interiorScore: 72,
        interiorReason: "新型CX-5のデザインコンセプト「ウェアラブル・ギア」に基づき、ボンネット先端の厚み、左右に広げたロアグリル、張り出したフェンダーなど、外装パーツの具体的な形状",
        imageInterior: true,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-00010003-carv-000-1-view.jpg",
        note: ""
    },
    {
        id: "jp5",
        title: "マイバッハSクラス、発光グリルと側面ロゴ投影を採用",
        desc: "メルセデス・ベンツ日本は9月15日、改良型マイバッハSクラスを発売した。VAGUEによると、約20％拡大したグリルはレタリングも発光し、側面にはブランド名を投影するライトを採用。リアコンビネーションランプの意匠も刷新した。",
        url: "https://news.yahoo.co.jp/articles/cba0c18152c77faf1159e60c8a45910ff9cca37f?source=rss",
        source: "VAGUE",
        date: "2026-09-15",
        tags: ["グリル", "照明・発光"],

        edition: "exterior", productScore: 92, exteriorScore: 92,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "フロントグリルは約20％拡大され、マイバッハのレタリングまで光るイルミネーテッド・ラジエターグリルを採用しました。",
        interiorScore: 92,
        interiorReason: "フロントグリルの拡大、イルミネーテッド・ラジエターグリル、ブランドロゴプロジェクターライト、リアコンビネーションランプなど、外装の具体的コンポーネント技術とデザ",
        imageInterior: false,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-10457244-vague-000-1-view.jpg",
        note: ""
    },
    {
        id: "jp6",
        title: "日産20-23の空力意匠を再考、市販化は筆者提案",
        desc: "2023年公開のコンセプト「20-23」の半円形LEDやエアロパーツを再紹介したコラム。筆者は新型マイクラへの意匠展開を提案しているが、日産による20-23の市販化発表ではない。",
        url: "https://news.yahoo.co.jp/articles/1d7b722ffefac6026d4abc6c8c0097bfdb3c6925?source=rss",
        source: "ベストカーWeb",
        date: "2026-09-15",
        tags: ["空力"],

        edition: "exterior", productScore: 72, exteriorScore: 72,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "デザインを示すために制作されたショーカーで、コンパクトなボディに大胆なエアロパーツを組み合わせ、レーシングカーを思わせるスタイルに仕上げられています。",
        interiorScore: 72,
        interiorReason: "日産コンセプトカーのフロントノーズ、LEDヘッドライト、エアロパーツ（スカート・ルーバー）など具体的な外装設計と機能性が詳述されており、コンパクトEVの外装デザ",
        imageInterior: true,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-00000013-bestcar-000-1-view.jpg",
        note: ""
    },
    {
        id: "jp7",
        title: "ヴェゼルの改良を予測、現行の外装とモデル動向を整理",
        desc: "くるまのニュースがホンダ「ヴェゼル」の一部改良の可能性を紹介。記事中のフロントグリル変更は2024年の実施内容で、現行車のクーペ風の車体形状も振り返っている。今後の変更仕様を確定するメーカー発表ではない。",
        url: "https://news.yahoo.co.jp/articles/d7be03cef16a87b8b31c91540e6239eb16bfffbd?source=rss",
        source: "くるまのニュース",
        date: "2026-09-15",
        tags: ["グリル"],

        edition: "exterior", productScore: 72, exteriorScore: 72,
        contentCategory: "trend", trendTopic: "competitor",
        sourceExcerpt: "2024年には初のマイナーチェンジが実施され、フロントグリルのデザインが変更されたほか、「e：HEV HuNTパッケージ」や「e：HEV PLaYパッケージ」が新たに設定されました。",
        interiorScore: 72,
        interiorReason: "ホンダヴェゼルの一部改良に関する記事で、フロントグリルデザインの変更や空力性能の追求といった具体的な外装設計要素が言及されている。主力SUVセグメントにおけるO",
        imageInterior: false,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-01110473-kurumans-000-1-view.jpg",
        note: ""
    },
    {
        id: "eu3",
        title: "ボルボXC60、グリル・灯火・前後バンパーを刷新し長距離PHEV化",
        desc: "ボルボはXC60のグリル、ボンネット、前フェンダー、前後バンパー、LED灯火を刷新。XC90とともに長距離PHEVを設定し、今秋の生産開始を予定する。米国向けの納車は2027年初めの予定。",
        url: "https://electriccarsreport.com/2026/09/volvo-xc60-and-xc90-get-long-range-plug-in-hybrid-power-with-up-to-78-miles-of-ev-range/",
        source: "Electric Cars Report",
        date: "2026-09-15",
        tags: ["グリル", "バンパー"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "At the rear, redesigned LED taillights, a revised tailgate and a new",
        sourceExcerptEnd: "lines and give the XC60 a wider, more confident stance.",
        interiorScore: 85,
        interiorReason: "XC60のグリル、バンパー、ヘッドライト（Thor's Hammer）、テールランプなど外装コンポーネントの具体的なデザイン刷新と機能変更が詳述されており、外装",
        imageInterior: false,
        country: "eu",
        img: "https://electriccarsreport.com/wp-content/uploads/2026/09/Volvo-XC60.jpg?a3781e&amp;a3781e",
        note: ""
    },
    {
        id: "eu4",
        title: "TADA 2026、Aion UTとGeely K011が外装デザイン賞",
        desc: "9月11〜13日のトリノモーターショーに合わせたTADAで、シティカー部門はGAC Aion UT、ファミリーカー部門はGeely K011が外装デザイン賞を受賞。欧州で展開中・進出予定の中国メーカーを対象とする賞。",
        url: "https://autodesignmagazine.com/en/2026/09/tada-2026-turin-rewards-the-design-of-chinese-cars/",
        source: "Auto & Design",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 75, exteriorScore: 75,
        contentCategory: "trend", trendTopic: "design",
        sourceExcerpt: "The ceremony, hosted at the Teatro Regio in Turin, awarded several awards,",
        sourceExcerptEnd: "the interior and the Geely Starray EM-i for technological innovation.",
        interiorScore: 75,
        interiorReason: "中国メーカーの欧州進出に伴うデザイン戦略の変化と、外装設計で評価された具体的なモデル（GAC Aion UT等）が示す競合動向は、外装プロダクト開発における意匠",
        imageInterior: false,
        country: "eu",
        img: "https://autodesignmagazine.com/wp-content/uploads/2026/09/2026091402_TadaGeely26.jpg?x17940",
        note: ""
    },
];
