window.LOADED_NEWS_DATA = [
    // 2026-09-14 (google検索からExcel sheet2_llm_targets)
    {
        id: "jp1",
        title: "レクサスLS改良でリアLマークがLEXUSバラ文字へ変更",
        desc: "トヨタは2026年9月10日、フラッグシップセダン「LS」の一部改良モデルを発売した。リア中央のエンブレムが従来の「L」マークから「LEXUS」のバラ文字に変更され、SNSではカッコいいという好評と威厳が失われたという惜しむ声が交錯している。",
        url: "https://news.yahoo.co.jp/articles/16a0805370a2422175e6e9cb042f8e45a9ede24d?source=rss",
        source: "VAGUE",
        date: "2026-09-14",
        tags: ["エンブレム"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        sourceExcerpt: "リア中央のブランドロゴが、「L」をかたどった従来仕様のエンブレムから、「LEXUS」の文字を一文字ずつ配置した“バラ文字エンブレム”に変更されています。",
        interiorScore: 85,
        interiorReason: "リアエンブレムのデザイン変更（Lマークからバラ文字へ）という具体的な外装コンポーネントの技術的・意匠的特徴が記事の中心であり、対象範囲に合致する。",
        imageInterior: false,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-10456791-vague-000-1-view.jpg",
        note: ""
    },
    {
        id: "us1",
        title: "BMW X5にカーボン製グリルとアラミド製ディフューザーを追加",
        desc: "BMWは2027年型X5向けに、カーボンファイバー製のグリルインサートやフロントスプリッター、アラミド素材のスポーティなディフューザーなど、M Performance Partsによる外装アクセサリーをラインナップした。",
        url: "https://www.carscoops.com/2026/09/2027-bmw-x5-m-performace-parts/",
        source: "CarScoops",
        date: "2026-09-14",
        tags: ["グリル", "材料"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        sourceExcerpt: "Starting up front, customers can get carbon fiber grille inserts as well as a carbon fiber front splitter.",
        interiorScore: 85,
        interiorReason: "カーボンファイバー製のグリルインサートとスプリッター、アラミド製ディフューザーという外装部品の素材と設計が記載されている。",
        imageInterior: false,
        country: "us",
        img: "https://www.carscoops.com/wp-content/uploads/2026/09/2027-BMW-X5-M-Performace-Pa-1024x578.jpg",
        note: ""
    },
    // 2026-09-15 (google検索からExcel sheet2_llm_targets)
    {
        id: "jp2",
        title: "ケンスタイルEIK、NDロードスターのフロント加飾事例を紹介",
        desc: "Auto Messe Webは2016年取材の事例として、ケンスタイル「EIK」のNDロードスターデモカーを紹介した。純正の雰囲気を生かすフロントハーフスポイラーに、リアはフジツボのオーソライズRMと専用ディフューザーを組み合わせる。マフラー本体はステンレス製で、青色のチタンテールを左右4本出しとした構成。",
        url: "https://news.yahoo.co.jp/articles/5003ae23c7e440ec545e3adff5659fdfccc8ca1e?source=rss",
        source: "Auto Messe Web",
        date: "2026-09-15",
        tags: ["過去事例", "外装加飾"],

        edition: "exterior", productScore: 65, exteriorScore: 65,
        sourceExcerpt: "ケンスタイルのエアロブランド「EIK」が選んだ答えは、オリジナルエアロをフロントハーフスポイラー1点に絞り、リアはフジツボ製チタンマフラーと専用ディフューザーのセットに任せる潔い構成だ。",
        interiorScore: 65,
        interiorReason: "NDロードスター用のフロントハーフスポイラーという具体的な外装エアロパーツの採用と、純正雰囲気を損なわないデザイン意図が記載されている。",
        imageInterior: false,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-00010008-amweb-000-1-view.jpg",
        note: "2016年取材の事例紹介。掲載日と製品発表日は異なります。"
    },
    {
        id: "us2",
        title: "次期AMG GT Black Series開発車、フェンダー上部の可動フラップを報道",
        desc: "CarScoopsは、ニュルブルクリンク近郊で撮影された次期AMG GT Black Seriesの開発車を紹介した。記事はフロントフェンダー上部の可動フラップ、ドア外板に沿って空気を流す側面ベント、スワンネック支柱の大型リアウイングを挙げる。フラップの開閉による圧力解放や空気抵抗低減は、記事筆者の推測として述べられている。",
        url: "https://www.carscoops.com/2026/09/amg-gt-black-series-looks-like-its-smashed-the-ring-record-before-its-even-hit-the-track/",
        source: "CarScoops",
        date: "2026-09-15",
        tags: ["開発車", "空力"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        sourceExcerpt: "sets of active flaps mounted in the top of each front fender",
        interiorScore: 85,
        interiorReason: "開発車のフロントフェンダー上部の可動フラップや側面ベントなど、具体的な外装コンポーネントが報道されている。用途の一部は記者の推測であり、性能は未確認。",
        imageInterior: false,
        country: "us",
        img: "https://www.carscoops.com/wp-content/uploads/2026/09/AMG-Black-scoop-Sep2614111-1024x576.jpg",
        note: "開発車の写真に基づく報道。量産仕様・性能の確定情報ではありません。"
    },
    // 2026-09-15 (google検索からExcel sheet2_llm_targets)
    {
        id: "jp3",
        title: "シエンタ、黒色ドアミラーと新ボディ色へ仕様整理",
        desc: "carview!が2026年8月のシエンタの一部改良を振り返った。全グレードのドアミラーをブラック加飾へ統一し、新色クリアベージュメタリックを追加。従来のベージュ、スカーレットメタリック、ツートーン色は廃止されたと紹介している。",
        url: "https://news.yahoo.co.jp/articles/6178ce0a6d838340cac6bbddc8be5bc302b0afa9?source=rss",
        source: "carview!",
        date: "2026-09-15",
        tags: ["外装加飾"],

        edition: "exterior", productScore: 72, exteriorScore: 72,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "さらに全グレードにおいて、これまでボディ同色だったドアミラーがブラック加飾に統一された。",
        interiorScore: 72,
        interiorReason: "トヨタシエンタの改良において、全グレードでドアミラーがブラック加飾に統一され、ボディカラーラインナップも見直された。外装パーツの意匠変更と色指定の整理は、エクス",
        imageInterior: false,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-00010011-carv-000-1-view.jpg",
        note: ""
    },
    {
        id: "us3",
        title: "AMG GLC 53改良開発車、グリルと星型灯火の変更を報道",
        desc: "Carscoopsが迷彩をまとったAMG GLC 53クーペのテスト車を紹介した。記事は新グリルと前後の星型の灯火意匠への変更を予測している。量産仕様の確定発表ではなく、開発車の写真に基づく報道。",
        url: "https://www.carscoops.com/2026/09/amgs-glc-is-getting-a-new-look-but-not-the-cle-646s-v8/",
        source: "CarScoops",
        date: "2026-09-15",
        tags: ["グリル"],

        edition: "exterior", productScore: 75, exteriorScore: 75,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "The visual changes will be subtle, focusing on a new grille and",
        sourceExcerptEnd: "cluster and angled console tablet found in the current car.",
        interiorScore: 75,
        interiorReason: "AMG GLCのマイナーチェンジにおいて、新グリルと星型DRLという具体的な外装部品のデザイン変更が言及されており、プレミアムSUVセグメントにおけるフロントマ",
        imageInterior: false,
        country: "us",
        img: "https://www.carscoops.com/wp-content/uploads/2026/09/AMG-GLC-lead-Sep152611-1024x576.jpg",
        note: ""
    },
    {
        id: "eu1",
        title: "JLR、ステランティスとディフェンダーのピックアップを検討と報道",
        desc: "AutocarはTimes報道を引用し、JLRがステランティスとの提携で北米向けディフェンダーのピックアップを検討していると伝えた。米国生産や採用する車台は未確定で、JLRは報道へのコメントを控えている。",
        url: "https://www.autocar.co.uk/car-news/new-cars/report-jlr-collaborating-stellantis-defender-pick",
        source: "AUTOCAR UK",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 75, exteriorScore: 75,
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "JLR is considering building a Defender pick-up as part of its new alliance with Stellantis, according to a report in The Times.",
        interiorScore: 75,
        interiorReason: "JLRとStellantisの提携によるDefenderピックアップ開発検討は、北米市場でのOEM戦略やプラットフォーム活用に関する具体的なシグナルであり、外装",
        imageInterior: false,
        country: "eu",
        img: "https://images.cdn.autocar.co.uk/sites/autocar.co.uk/files/styles/car_review_image_190/public/images/car-reviews/first-drives/legacy/land_rover_defender_crew_1_1.jpg?itok=qyvuFzaN",
        note: ""
    },
    {
        id: "eu2",
        title: "アウディRS Q5とみられる開発車、角形グリルと縦長吸気口",
        desc: "Auto Expressは、RS Q5とみられる開発車の小型フェンダー拡張部、角張ったグリル、その両側の縦長で細い吸気口、後部の大型楕円形排気口を報じた。撮影車はスポーツバック型で、量産仕様・出力・発売時期は未確定。",
        url: "https://www.autoexpress.co.uk/audi/q5/370434/first-ever-audi-rs-q5-spied-massive-phev-power-and-snarling-style",
        source: "Auto Express",
        date: "2026-09-15",
        tags: ["グリル"],

        edition: "exterior", productScore: 82, exteriorScore: 82,
        contentCategory: "trend", trendTopic: "competitor",
        sourceExcerpt: "This is obvious with the prototype’s grille, which has a squarer shape, flanked by two tall and narrow outer intakes.",
        interiorScore: 82,
        interiorReason: "アウディRS Q5のプロトタイプにおいて、角張ったグリル形状や外側インテーク、フェンダー延長など具体的なエクステリアデザイン変更が報告されており、競合他社の最新",
        imageInterior: false,
        country: "eu",
        img: "https://media.autoexpress.co.uk/image/private/s--DXyJF5fN--/t_rss_image_w_845/v1789463067/autoexpress/2026/09/New%20Audi%20RS%20Q5%20Sportback%20001.jpg",
        note: ""
    },
    {
        id: "cn1",
        title: "Voyah Dream 9、格納式発光オーナメントを採用",
        desc: "東風傘下のVoyahは旗艦MPV「Dream 9」を9月22日に発売すると発表した。縦型クロームグリルと格納式の発光フードオーナメント、Huawei Xpixel投影ヘッドライトを備え、ツートーンの外装を用意する。",
        url: "https://carnewschina.com/2026/09/15/voyah-dream-9-flagship-mpv-with-701-km-range-set-to-launch-on-september-22/",
        source: "CarNewsChina - All",
        date: "2026-09-15",
        tags: ["グリル", "照明・発光"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "It is equipped with Huawei Xpixel smart projection headlights.",
        interiorScore: 85,
        interiorReason: "「Dragon Scale」グリル、リトラクタブル式イルミネーションエンブレム、Huawei Xpixelヘッドライトなど、外装コンポーネントの具体的な設計と機",
        imageInterior: false,
        country: "cn",
        img: "https://carnewschina.com/wp-content/uploads/2026/09/e59bbee78987-110-e1789454207654.png",
        note: ""
    },
    {
        id: "cn2",
        title: "フリーランダー8、中国で9月19日納車開始へ",
        desc: "奇瑞ジャガー・ランドローバーは「フリーランダー8」の中国納車を9月19日に始めると発表した。Concept 97を由来とする箱型の外観に、閉じたフロントマスクと長方形ヘッドライトを組み合わせ、ルーフ上にLiDARを配置する。",
        url: "https://carnewschina.com/2026/09/15/freelander-8-china-deliveries-to-begin-september-19/",
        source: "CarNewsChina - All",
        date: "2026-09-15",
        tags: ["照明・発光"],

        edition: "exterior", productScore: 74, exteriorScore: 74,
        contentCategory: "trend", trendTopic: "competitor",
        sourceExcerpt: "The front fascia features a closed-off design paired with rectangular headlights.",
        interiorScore: 74,
        interiorReason: "中国市場での発売開始と12時間5,000台の受注実績という具体的な市場データに加え、フロントマスクのクローズドデザインやLiDAR搭載など外装設計に関する記述が",
        imageInterior: false,
        country: "cn",
        img: "https://carnewschina.com/wp-content/uploads/2026/09/e59bbee78987-109-e1789435232593_webhook_1500x900_q85_1789435476.jpg",
        note: ""
    },
    {
        id: "in1",
        title: "マルチ・スズキ ワゴンR改良型の開発車、グリルやバンパーを変更",
        desc: "Autocar IndiaがワゴンRの開発車を報道。ヘッドランプの細部やグリル、前部の吸気口に変更が見られ、後部バンパーの反射板は横型から縦型になっている。市販仕様は記事時点で未確定。",
        url: "https://www.autocarindia.com/car-news/maruti-suzuki-wagon-r-facelift-spied-testing-440755",
        source: "Autocar India - All",
        date: "2026-09-15",
        tags: ["グリル", "バンパー", "照明・発光"],

        edition: "exterior", productScore: 62, exteriorScore: 62,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "The test mule was spotted with new detailing for the halogen headlamps,",
        sourceExcerptEnd: "finish for the bumper and redesigned air inlets lower down.",
        interiorScore: 62,
        interiorReason: "ワゴンRのフェイスリフトにおいて、グリル形状の変更やヘッドランプ意匠の更新、バンパーおよびエアインレットのデザイン変更といった具体的な外装パーツの計画が示唆され",
        imageInterior: false,
        country: "in",
        img: "https://asset.autocarindia.com/static/news/images/20260915_114450_cc6f12d9.jpg",
        note: ""
    },
    {
        id: "in2",
        title: "フェラーリ296 GT Modificata、新スプリッターと大型固定翼",
        desc: "フェラーリはサーキット専用の296 GT Modificataを発表。前部スプリッターと冷却用吸気口を改め、後部ウィングは中央支柱や5mmのガーニーフラップなどを更新した。GT3 Evoを基にした顧客向け限定車。",
        url: "https://www.autocarindia.com/car-news/ferrari-296-gt-modificata-debuts-as-supercars-most-extreme-version-yet-440754",
        source: "Autocar India - All",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "The exhaust tips are also of a completely new design for the",
        sourceExcerptEnd: "is barely unchanged from the one on the GT3 Evo.",
        interiorScore: 85,
        interiorReason: "フェラーリ296 GT Modificataの空力コンポーネント（フロントスポイラー、リアウィング、Gurneyフラップ、エアインテーク）の詳細な設計と機能に関",
        imageInterior: false,
        country: "in",
        img: "https://asset.autocarindia.com/static/news/images/20260915_111105_dd098842.jpg",
        note: ""
    },
    {
        id: "in3",
        title: "BMW i5 LWBをインドで試乗、発光グリルとM専用バンパー",
        desc: "RushLaneがインド仕様のBMW i5 LWBを試乗。発光キドニーグリル、M専用前後バンパー、窓枠とCピラーのサテン仕上げ、20インチMエアロホイールを紹介した。価格は796万ルピーから（現地車両価格）。",
        url: "https://www.rushlane.com/bmw-i5-lwb-review-spacious-fast-and-surprisingly-fun-12555908.html",
        source: "RushLane",
        date: "2026-09-15",
        tags: ["グリル", "バンパー", "照明・発光"],

        edition: "exterior", productScore: 74, exteriorScore: 74,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "I liked Hofmeister kink and 5 labelling on C Pillar, BMW kidney",
        sourceExcerptEnd: "even the 20-inch M aero wheels (245-section front, 275-section rear).",
        interiorScore: 74,
        interiorReason: "BMW i5 LWBのレビュー記事であり、Illuminated Kidney Grille（発光キドニーグリル）、M専用フロント/リアバンパー、アルミサテン仕",
        imageInterior: true,
        country: "in",
        img: "https://www.rushlane.com/wp-content/uploads/2026/09/bmw-i5-lwb-review-cover.jpg",
        note: ""
    },
    {
        id: "in4",
        title: "Wrangler JL-2A、民生用CJ-2Aを着想源に外装配色を変更",
        desc: "1945年の民生用ウィリスCJ-2Aに着想を得た装備パッケージ。オレンジ系のホイールと牽引フック、7スロットグリルの濃灰色アクセントを採用する。記事では追加価格4,995米ドル、10月受注開始としている。",
        url: "https://www.rushlane.com/jeep-wrangler-pays-tribute-to-iconic-willys-jeep-from-world-war-ii-era-12555851.html",
        source: "RushLane",
        date: "2026-09-15",
        tags: ["グリル"],

        edition: "exterior", productScore: 74, exteriorScore: 74,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "These include a Dark Metallic Grey accent for the iconic seven slot grille.",
        interiorScore: 74,
        interiorReason: "Wrangler JL-2A特別パッケージにおいて、7スロットグリルのダークメタリックグレーアクセントやJooseカラーホイール、オレンジ色トウフックなど外装コ",
        imageInterior: true,
        country: "in",
        img: "https://www.rushlane.com/wp-content/uploads/2026/09/jeep-wrangler-willys-edition-launch-price-4.jpg",
        note: ""
    },
    {
        id: "in5",
        title: "Denza D9・Z9 GTのインド導入観測、グリルや後部意匠を紹介",
        desc: "RushLaneはDenza D9とZ9 GTのインド導入見通しを報じた。既存車の意匠として、D9の縦桟グリル、Z9 GTの前後LED照明と大型リアディフューザーを紹介。導入時期やインド仕様は未確定。",
        url: "https://www.rushlane.com/byd-denza-d9-luxury-mpv-and-z9-gt-1156-bhp-fastback-india-launch-soon-12555798.html",
        source: "RushLane",
        date: "2026-09-15",
        tags: ["グリル", "照明・発光"],

        edition: "exterior", productScore: 70, exteriorScore: 70,
        contentCategory: "trend", trendTopic: "competitor",
        sourceExcerpt: "Front fascia has a large and imposing grille with vertical slats, while rear is flat, with interesting LED tail light signature.",
        interiorScore: 70,
        interiorReason: "BYD Denza D9とZ9 GTのインド市場投入に関する記事で、フロントグリル形状やLEDライトシグネチャー、リアディフューザーなど外装デザイン要素が具体的",
        imageInterior: true,
        country: "in",
        img: "https://www.rushlane.com/wp-content/uploads/2026/09/byd-denza-d9-and-z9-gt-india.jpg",
        note: ""
    },
    {
        id: "in6",
        title: "次期タタNexon開発車、Aピラーやリアスポイラー変更の可能性",
        desc: "IndiaCarNewsは次期Nexonの試験車を紹介。写真からAピラー、後部ドア、スポイラーに小変更があると推測する。新テールランプやバンパーの採用は予想段階で、市販仕様は未確定。",
        url: "https://www.indiacarnews.com/news/new-rs-8-lakh-tata-suv-coming-in-2027-with-new-platform-69005/",
        source: "IndiaCarNews",
        date: "2026-09-15",
        tags: ["バンパー", "照明・発光"],

        edition: "exterior", productScore: 74, exteriorScore: 74,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "The SUV might also receive newly-designed LED taillamps, revised tailgate and bumper.",
        interiorScore: 74,
        interiorReason: "次期型NexonのAピラー、リアスポイラー、LEDテールランプおよびバンパーの変更が具体的に言及されており、外装デザイン計画に有用な情報を含む。",
        imageInterior: false,
        country: "in",
        img: "https://www.indiacarnews.com/wp-content/uploads/2026/06/New-Tata-Nexon-2027-Launch.webp",
        note: ""
    },
    {
        id: "in7",
        title: "ヒョンデの新SUV開発車、H字型ライトとグリルの意匠を報道",
        desc: "IndiaCarNewsはBayonとする開発車の角形ホイールアーチ、スラットグリル、H字型LEDデイライトを紹介。価格約100万ルピーから、数週間内の発売はいずれも同媒体の見通しで、公式仕様は未公表。",
        url: "https://www.indiacarnews.com/news/new-rs-10-lakh-hyundai-suv-launching-soon-victoris-rival-69002/",
        source: "IndiaCarNews",
        date: "2026-09-15",
        tags: ["グリル", "照明・発光"],

        edition: "exterior", productScore: 75, exteriorScore: 75,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "Upfront, the SUV will feature a slatted grille, H-styled top-mounted LED DRLs, LED headlamps in trapezoidal housing and a sporty bumper.",
        interiorScore: 75,
        interiorReason: "ヒュンダイ新SUVベイオンの外装デザイン（スラットグリル、H型LED DRL、トラペゾイド形状ヘッドランプ、スポーティバンパー）が具体的に記載されており、競合モ",
        imageInterior: false,
        country: "in",
        img: "https://www.indiacarnews.com/wp-content/uploads/2026/09/Untitled-Design-13.webp",
        note: ""
    },
    {
        id: "jp4",
        title: "新型CX-5の受注動向、販売店では上級Lが好評",
        desc: "carview!は、5月発売の新型CX-5が6月21日時点で国内受注1万台を超えたと紹介した。取材した販売店の声として、室内空間の広さへの評価や上級グレード「L」の人気を報道。受注実績と販売店への取材から、ミッドサイズSUVの需要を振り返る記事。",
        url: "https://news.yahoo.co.jp/articles/8d8604452771a7888ed61e760510c7ff5d59f4f9?source=rss",
        source: "carview!",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 72, exteriorScore: 72,
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "2026年5月21日に新型CX-5が発売され、約1か月後の6月21日時点で、国内受注台数が1万台を超え、月間販売計画2000台の5倍以上に達しています。",
        interiorScore: 72,
        interiorReason: "新型CX-5のデザインコンセプト「ウェアラブル・ギア」に基づき、ボンネット先端の厚み、左右に広げたロアグリル、張り出したフェンダーなど、外装パーツの具体的な形状",
        imageInterior: true,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-00010003-carv-000-1-view.jpg",
        note: ""
    },
    {
        id: "jp5",
        title: "マイバッハSクラス、発光グリルと側面ロゴ投影を採用",
        desc: "メルセデス・ベンツ日本は9月15日、改良型マイバッハSクラスを発売した。VAGUEによると、約20％拡大したグリルはレタリングも発光し、側面にはブランド名を投影するライトを採用。リアコンビネーションランプの意匠も刷新した。",
        url: "https://news.yahoo.co.jp/articles/cba0c18152c77faf1159e60c8a45910ff9cca37f?source=rss",
        source: "VAGUE",
        date: "2026-09-15",
        tags: ["グリル", "照明・発光"],

        edition: "exterior", productScore: 92, exteriorScore: 92,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "フロントグリルは約20％拡大され、マイバッハのレタリングまで光るイルミネーテッド・ラジエターグリルを採用しました。",
        interiorScore: 92,
        interiorReason: "フロントグリルの拡大、イルミネーテッド・ラジエターグリル、ブランドロゴプロジェクターライト、リアコンビネーションランプなど、外装の具体的コンポーネント技術とデザ",
        imageInterior: false,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-10457244-vague-000-1-view.jpg",
        note: ""
    },
    {
        id: "jp6",
        title: "日産20-23の空力意匠を再考、市販化は筆者提案",
        desc: "2023年公開のコンセプト「20-23」の半円形LEDやエアロパーツを再紹介したコラム。筆者は新型マイクラへの意匠展開を提案しているが、日産による20-23の市販化発表ではない。",
        url: "https://news.yahoo.co.jp/articles/1d7b722ffefac6026d4abc6c8c0097bfdb3c6925?source=rss",
        source: "ベストカーWeb",
        date: "2026-09-15",
        tags: ["空力"],

        edition: "exterior", productScore: 72, exteriorScore: 72,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "デザインを示すために制作されたショーカーで、コンパクトなボディに大胆なエアロパーツを組み合わせ、レーシングカーを思わせるスタイルに仕上げられています。",
        interiorScore: 72,
        interiorReason: "日産コンセプトカーのフロントノーズ、LEDヘッドライト、エアロパーツ（スカート・ルーバー）など具体的な外装設計と機能性が詳述されており、コンパクトEVの外装デザ",
        imageInterior: true,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-00000013-bestcar-000-1-view.jpg",
        note: ""
    },
    {
        id: "jp7",
        title: "ヴェゼルの改良を予測、現行の外装とモデル動向を整理",
        desc: "くるまのニュースがホンダ「ヴェゼル」の一部改良の可能性を紹介。記事中のフロントグリル変更は2024年の実施内容で、現行車のクーペ風の車体形状も振り返っている。今後の変更仕様を確定するメーカー発表ではない。",
        url: "https://news.yahoo.co.jp/articles/d7be03cef16a87b8b31c91540e6239eb16bfffbd?source=rss",
        source: "くるまのニュース",
        date: "2026-09-15",
        tags: ["グリル"],

        edition: "exterior", productScore: 72, exteriorScore: 72,
        contentCategory: "trend", trendTopic: "competitor",
        sourceExcerpt: "2024年には初のマイナーチェンジが実施され、フロントグリルのデザインが変更されたほか、「e：HEV HuNTパッケージ」や「e：HEV PLaYパッケージ」が新たに設定されました。",
        interiorScore: 72,
        interiorReason: "ホンダヴェゼルの一部改良に関する記事で、フロントグリルデザインの変更や空力性能の追求といった具体的な外装設計要素が言及されている。主力SUVセグメントにおけるO",
        imageInterior: false,
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-01110473-kurumans-000-1-view.jpg",
        note: ""
    },
    {
        id: "eu3",
        title: "ボルボXC60、グリル・灯火・前後バンパーを刷新し長距離PHEV化",
        desc: "ボルボはXC60のグリル、ボンネット、前フェンダー、前後バンパー、LED灯火を刷新。XC90とともに長距離PHEVを設定し、今秋の生産開始を予定する。米国向けの納車は2027年初めの予定。",
        url: "https://electriccarsreport.com/2026/09/volvo-xc60-and-xc90-get-long-range-plug-in-hybrid-power-with-up-to-78-miles-of-ev-range/",
        source: "Electric Cars Report",
        date: "2026-09-15",
        tags: ["グリル", "バンパー"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "At the rear, redesigned LED taillights, a revised tailgate and a new",
        sourceExcerptEnd: "lines and give the XC60 a wider, more confident stance.",
        interiorScore: 85,
        interiorReason: "XC60のグリル、バンパー、ヘッドライト（Thor's Hammer）、テールランプなど外装コンポーネントの具体的なデザイン刷新と機能変更が詳述されており、外装",
        imageInterior: false,
        country: "eu",
        img: "https://electriccarsreport.com/wp-content/uploads/2026/09/Volvo-XC60.jpg?a3781e&amp;a3781e",
        note: ""
    },
    {
        id: "eu4",
        title: "TADA 2026、Aion UTとGeely K011が外装デザイン賞",
        desc: "9月11〜13日のトリノモーターショーに合わせたTADAで、シティカー部門はGAC Aion UT、ファミリーカー部門はGeely K011が外装デザイン賞を受賞。欧州で展開中・進出予定の中国メーカーを対象とする賞。",
        url: "https://autodesignmagazine.com/en/2026/09/tada-2026-turin-rewards-the-design-of-chinese-cars/",
        source: "Auto & Design",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 75, exteriorScore: 75,
        contentCategory: "trend", trendTopic: "design",
        sourceExcerpt: "The ceremony, hosted at the Teatro Regio in Turin, awarded several awards,",
        sourceExcerptEnd: "the interior and the Geely Starray EM-i for technological innovation.",
        interiorScore: 75,
        interiorReason: "中国メーカーの欧州進出に伴うデザイン戦略の変化と、外装設計で評価された具体的なモデル（GAC Aion UT等）が示す競合動向は、外装プロダクト開発における意匠",
        imageInterior: false,
        country: "eu",
        img: "https://autodesignmagazine.com/wp-content/uploads/2026/09/2026091402_TadaGeely26.jpg?x17940",
        note: ""
    },
    // 2026-09-09 (google検索からExcel sheet2_llm_targets)
    {
        id: "eu7",
        title: "VWアマロック特別仕様、ルーフレールやバンパーを光沢黒に",
        desc: "Auto ExpressはAmarok Dark Labelを紹介。クローム加飾の多くを光沢黒に置き換え、ルーフレール、バンパー、前面、外側ミラーなどを仕上げる。20インチホイールも黒色とし、車体色は黒・青・灰のメタリックを設定。",
        url: "https://www.autoexpress.co.uk/volkswagen/amarok/370396/new-volkswagen-amarok-dark-label-special-edition-cancels-out-chrome",
        source: "Auto Express Car News",
        date: "2026-09-09",
        tags: ["バンパー", "外装加飾"],

        edition: "exterior", productScore: 76, exteriorScore: 76,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "While the Amarok’s Ford Ranger underpinnings and basic design remain the same,",
        sourceExcerptEnd: "and gets lashings of gloss black paint in its place.",
        interiorScore: 76,
        interiorReason: "ピックアップの特別仕様で、表面仕上げの置換部位とホイール・車体色が具体的。外装加飾の展開方法の比較対象になる。",
        country: "eu",
        img: "https://media.autoexpress.co.uk/image/private/s--X-WVjvBW--/f_auto,t_content-image-full-desktop@1/v1788946694/autoexpress/2026/09/Volkswagen Amarok Dark Label-3.jpg",
        note: ""
    },
    // 2026-09-10 (google検索からExcel sheet2_llm_targets)
    {
        id: "us7",
        title: "米国向けボルボXC40改良型、グリルと灯火・前後外装を刷新",
        desc: "2028年式ボルボXC40は前部パネル、細いグリル、新メッシュ、マトリクスLED灯火を採用。後部もテールランプ、テールゲート、バンパーとホイール意匠を変更する。ベルギー生産で、米国販売は2027年第1四半期を予定。価格は未公表。",
        url: "https://www.caranddriver.com/news/a73647209/2028-volvo-xc40-refresh-revealed/",
        source: "Car and Driver",
        date: "2026-09-10",
        tags: ["グリル", "バンパー", "照明・発光"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "The XC40’s distinctive LED taillights have been sculpted to look thinner, and the liftgate has been massaged to match the new rear bumper.",
        interiorScore: 85,
        interiorReason: "グリル・灯火・バンパーなど具体的な外装変更が複数ある。既掲載XC60とは別モデル。記事の量産・発売予定を確定実施と誤記しない。",
        country: "us",
        img: "https://hips.hearstapps.com/hmg-prod/images/622a5ae0-b38b-4c27-be29-98d2f4adf1a7.jpg?crop=1xw:0.667xh;0xw,0.157xh&resize=1200:*",
        note: ""
    },
    {
        id: "cn8",
        title: "中国9月第1週のNEV小売15万台、乗用車に占める割合71.5％",
        desc: "CPCAの9月10日公表値では、9月1〜6日の中国乗用NEV小売は15万台、前年比3％減、前月同期間比15％増。乗用車全体は21万台、前年比19％減でNEV比率は71.5％となった。構成比上昇と台数増は別で、前年の補助金終了前需要という比較要因もある。",
        url: "https://cnevpost.com/2026/09/10/china-nev-retail-first-week-sept-2026/",
        source: "CnEVPost - All",
        date: "2026-09-10",
        tags: [],

        edition: "exterior", productScore: 86, exteriorScore: 86,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "China's new energy vehicle (NEV) retail sales picked up at the start",
        sourceExcerptEnd: "last month, though the broader auto market remained under pressure.",
        interiorScore: 86,
        interiorReason: "期間・母数・小売と卸売を区別できる需要統計。単なる部品名有無に依存しない市場候補。",
        country: "cn",
        img: "https://cnevpost.com/wp-content/uploads/2026/09/2026091009084368.jpg",
        note: ""
    },
    {
        id: "in10",
        title: "ヒョンデLounge Edition、黒色スキッドプレートとサイド加飾を追加",
        desc: "ヒョンデはインドでCreta、Alcazar、Creta ElectricのLounge Editionを設定。Car Blog Indiaによると、18インチのマットブラックホイール、黒塗装の前後スキッドプレート、サイドシル加飾、新色Golden Bronzeを採用する。",
        url: "https://www.carblogindia.com/hyundai-lounge-edition-creta-alcazar-creta-electric-launched/",
        source: "Car Blog India",
        date: "2026-09-10",
        tags: ["外装加飾"],

        edition: "exterior", productScore: 76, exteriorScore: 76,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "These SUVs also get a bold and premium black treatment, 18-inch Matte",
        sourceExcerptEnd: "garnish and a new Golden Bronze colour for the exterior.",
        interiorScore: 76,
        interiorReason: "内装中心の特別仕様紹介だが、前後スキッドプレート、サイドシル、ホイール、外板色という具体的な外装部位の変更も明記される。黒色化と配色の比較対象として適格。",
        country: "in",
        img: "https://www.carblogindia.com/wp-content/uploads/2026/09/hyundai-lounge-edition-creta-alcazar-creta-electric.jpg",
        note: ""
    },
    // 2026-09-11 (google検索からExcel sheet2_llm_targets)
    {
        id: "us6",
        title: "ボルボEX40、米国販売を2026年モデルで終了へ",
        desc: "ボルボはEX40の米国販売を2026年モデルで終了するとCar and Driverに確認した。記事はガソリン車XC40に比べ小さい販売規模を背景に挙げる。後継EX50の登場時期や価格は未確定の報道で、販売終了の確認事実とは区別する。",
        url: "https://www.caranddriver.com/news/a73670980/volvo-ex40-canceled/",
        source: "Car and Driver",
        date: "2026-09-11",
        tags: [],

        edition: "exterior", productScore: 75, exteriorScore: 75,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "Volvo has officially canceled the EX40 electric compact luxury SUV, the automaker confirmed to Car and Driver.",
        interiorScore: 75,
        interiorReason: "メーカーへの確認がある米国モデル廃止と需要動向。新XC40の外装変更とは車種・主題が別。後継の未確認価格を採用しない。",
        country: "us",
        img: "https://hips.hearstapps.com/hmg-prod/images/2025-volvo-ex40-twin-motor-ultra-361-67bf33046db4a.jpg?crop=0.769xw:0.577xh;0.166xw,0.375xh&resize=1200:*",
        note: ""
    },
    {
        id: "us8",
        title: "AMG CLE 646、カーボン外装と調整式リアウイングを採用",
        desc: "米Car and Driverは独メルセデスAMGの限定30台CLE 646を報道。フェンダー、ボンネット、ルーフ、リアバンパー等にカーボンを使い、後部窓はポリカーボネート製。冷却開口、大型ディフューザー、中央部を手動調整できるリアウイングを備える。",
        url: "https://www.caranddriver.com/news/a73674190/mercedes-amg-cle-646-spezialanfertigung-revealed/",
        source: "Car and Driver",
        date: "2026-09-11",
        tags: ["バンパー"],

        edition: "exterior", productScore: 86, exteriorScore: 86,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "Those bulging front fenders, which have huge air outlets carved into them,",
        sourceExcerptEnd: "the front end, side sills, hood, roof, and rear bumper.",
        interiorScore: 86,
        interiorReason: "材料、対象パネル、冷却開口と空力部品が本文で特定できる。駆動性能だけの記事ではない。既掲載AMG GT/GLCとは別モデル。",
        country: "us",
        img: "https://hips.hearstapps.com/hmg-prod/images/74068024-4c57-4c4b-873b-5b34fab67ba6.jpg?crop=0.54xw:0.405xh;0.213xw,0.293xh&resize=1200:*",
        note: ""
    },
    {
        id: "us10",
        title: "8月の北米EV販売は前年同月比33％減、欧州とは方向が分かれる",
        desc: "Benchmark集計を紹介したElectrekによると、2026年8月の北米EV販売は約14万台で前年比33％減、前月比5％増。欧州は約38万台で前年比36％増だった。北米の前年比には前年の米国税額控除終了前の駆け込みと供給変化も影響する。",
        url: "https://electrek.co/2026/09/10/ev-sales-are-booming-in-europe-and-plunging-in-north-america/",
        source: "Electrek",
        date: "2026-09-11",
        tags: [],

        edition: "exterior", productScore: 84, exteriorScore: 84,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "Around 1.83 million EVs were sold worldwide in August, according to Benchmark Mineral Intelligence.",
        interiorScore: 84,
        interiorReason: "期間・地域・比較基準が明確な市場実績。米国単独の台数と誤記せず北米値として扱う。",
        country: "us",
        img: "https://electrek.co/wp-content/uploads/sites/3/2026/05/Volvo-cheaper-EV-EX30.jpeg?quality=82&strip=all&resize=1200,628",
        note: ""
    },
    {
        id: "cn5",
        title: "Onvo L80、新青色塗装と21インチホイールの外装パッケージ",
        desc: "中国OnvoはL80向けStarlight外装パッケージを発売。新色Xinghan Blueと専用21インチ多スポークホイールを組み合わせ、9月30日までの注文は1万80元。月次納車が3か月連続減となる中での外観施策で、駆動系や電池の改良は発表していない。",
        url: "https://cnevpost.com/2026/09/11/nio-onvo-launches-l80-styling-package/",
        source: "CnEVPost - All",
        date: "2026-09-11",
        tags: ["外装加飾"],

        edition: "exterior", productScore: 87, exteriorScore: 87,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        interiorScore: 87,
        interiorReason: "塗装・ホイール意匠と販売背景を直接結び付ける強い外装事例。価格は元表記を正確に円換算せず記載。",
        country: "cn",
        img: "https://cnevpost.com/wp-content/uploads/2026/09/2026091105520510.jpg",
        note: ""
    },
    {
        id: "cn6",
        title: "中国Model Y Performance、専用前後フェイシアとカーボン製スポイラー",
        desc: "テスラは9月11日、中国でModel Y Performanceを発売。専用前後フェイシア、カーボン製スポイラー、21インチホイール、赤いキャリパーを備える。開始価格36万9000元、納期2〜6週間。中国Model Yの納車が3か月連続前年比減となる中での仕様拡充。",
        url: "https://cnevpost.com/2026/09/11/tesla-launches-model-y-performance-china/",
        source: "CnEVPost - All",
        date: "2026-09-11",
        tags: [],

        edition: "exterior", productScore: 82, exteriorScore: 82,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "It features aerodynamic front and rear fascias, a carbon-fiber spoiler, standard 21-inch Arachnid 2.0 wheels and red brake calipers.",
        interiorScore: 82,
        interiorReason: "前後部材・材料・外観差の具体性が十分。加速性能の紹介だけではない。",
        country: "cn",
        img: "https://cnevpost.com/wp-content/uploads/2026/09/2026091101185539.jpg",
        note: ""
    },
    {
        id: "cn7",
        title: "中国MG 07、発売20日間で確定注文4万2000台超",
        desc: "中国MG 07は8月21日発売後、9月10日までの20日間で確定注文4万2000台超を獲得したとMGが発表。航続距離800km超の仕様が注文の45％超を占める。電気・PHEV計7仕様で期間限定10万5900元から。数字は受注であり納車台数ではない。",
        url: "https://cnevpost.com/2026/09/11/mg-07-locked-in-orders-42000-20-days/",
        source: "CnEVPost - All",
        date: "2026-09-11",
        tags: [],

        edition: "exterior", productScore: 78, exteriorScore: 78,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "market",
        interiorScore: 78,
        interiorReason: "具体的な受注期間・仕様選択の傾向があり、乗用車の需要把握に有用。注文と販売実績を区別。",
        country: "cn",
        img: "https://cnevpost.com/wp-content/uploads/2026/09/2026091112180323.jpg",
        note: ""
    },
    {
        id: "cn9",
        title: "中国の2026〜2030年NEV計画、乗用車販売比率70％を目標",
        desc: "中国の工業情報化部など9部門が示す2026〜2030年NEV産業計画は、2030年に国内新車乗用車販売の70％をNEVとする目標を掲げる。高度自動運転の展開、生産能力の監督や再編も促す。将来の政策目標で、現時点の販売比率や外装部品規格の改定ではない。",
        url: "https://cnevpost.com/2026/09/11/china-unveils-five-year-nev-plan/",
        source: "CnEVPost - All",
        date: "2026-09-11",
        tags: [],

        edition: "exterior", productScore: 79, exteriorScore: 79,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "regulation",
        interiorScore: 79,
        interiorReason: "工業政策として対象年・販売母数・将来目標が明示。外装単独の安全規格や現在の達成値にすり替えない。",
        country: "cn",
        img: "https://cnevpost.com/wp-content/uploads/2026/09/2026091102004865.jpg",
        note: ""
    },
    {
        id: "cn10",
        title: "一汽VWのID. AURA T6、9月20日の中国発売へ",
        desc: "一汽VWは電動SUVのID. AURA T6を9月20日に中国発売予定。8月28日開始の先行予約は4仕様、13万5900〜16万9900元。上位2仕様は192チャンネルLiDARを搭載し、VWとXpeng共同開発のCEA電子アーキテクチャを採用する。",
        url: "https://cnevpost.com/2026/09/11/faw-vw-launch-id-aura-t6-sept-20/",
        source: "CnEVPost - All",
        date: "2026-09-11",
        tags: [],

        edition: "exterior", productScore: 71, exteriorScore: 71,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "competitor",
        interiorScore: 71,
        interiorReason: "発売予定・価格帯・装備差が本文で確認できる競合市場情報。センサーカバー形状など未記載の外装構造を創作しない。",
        country: "cn",
        img: "https://cnevpost.com/wp-content/uploads/2026/09/2026091107243211.jpg",
        note: ""
    },
    // 2026-09-12 (google検索からExcel sheet2_llm_targets)
    {
        id: "us9",
        title: "IONIQ 6 Nの米国導入準備、専用バンパーと大型リアウイング",
        desc: "ヒョンデIONIQ 6 Nは米国で2026年内の限定供給を予定。公道で捉えた車両には、ワイドで低く見せる意匠、大型リアウイングとスポイラー、専用前後バンパー、Nバッジが見られる。Electrek記事時点の米国価格は未発表。",
        url: "https://electrek.co/2026/09/11/hyundais-ioniq-6-n-looks-ready-us-launch-image/",
        source: "Electrek",
        date: "2026-09-12",
        tags: ["バンパー"],

        edition: "exterior", productScore: 79, exteriorScore: 79,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "It also gains a massive ducktail wing and spoiler, modified front and rear bumpers, and exclusive N badges.",
        interiorScore: 79,
        interiorReason: "米国投入予定と写真説明にある外装差別化を確認。出力数値や未発表価格を主題にせず、発売済みとも記述しない。",
        country: "us",
        img: "https://electrek.co/wp-content/uploads/sites/3/2026/09/Hyundai-IONIQ-6-N-US-launch-1.jpeg?quality=82&strip=all&resize=1200,628",
        note: ""
    },
    {
        id: "us11",
        title: "米国のEV平均購入価格は8月に低下、新車全体との差は9.4％へ",
        desc: "Kelley Blue Bookによる2026年8月の米国EV平均取引価格は5万4813ドルで、前月比1.2％、前年比2.7％低下。新車全体の平均5万89ドルとの差は9.4％へ縮小した。値引きや車種構成を含む平均値で、各車の定価の一律値下げを意味しない。",
        url: "https://electrek.co/2026/09/11/ev-prices-are-falling-while-the-average-new-car-tops-50k/",
        source: "Electrek",
        date: "2026-09-12",
        tags: [],

        edition: "exterior", productScore: 84, exteriorScore: 84,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "New EV buyers paid an average of $54,813 in August, according to Kelley Blue Book.",
        interiorScore: 84,
        interiorReason: "購入価格と販売奨励金の実測データで市場比較に有用。平均価格と定価、同車種価格差の混同を回避。",
        country: "us",
        img: "https://electrek.co/wp-content/uploads/sites/3/2026/09/2026-tesla-model-y-driving-front-3qtr.jpg?quality=82&strip=all&resize=1200,628",
        note: ""
    },
    {
        id: "cn4",
        title: "VW中国ID. UNYX 08、黒色ボディと専用ホイールの仕様を追加",
        desc: "VW安徽は中国のID. UNYX 08にLieying仕様を追加。黒色ボディと専用21インチ黒色ホイール、オレンジのキャリパーで外観を差別化する。同時に通常仕様の期間限定開始価格を18万9900元へ引き下げた。外観仕様と価格施策を組み合わせた更新。",
        url: "https://cnevpost.com/2026/09/12/vw-anhui-refreshes-id-unyx-08-suv/",
        source: "CnEVPost - All",
        date: "2026-09-12",
        tags: [],

        edition: "exterior", productScore: 73, exteriorScore: 73,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        interiorScore: 73,
        interiorReason: "外観パッケージの具体色・ホイール仕様があり、単なる値下げ記事より外装への情報寄与がある。",
        country: "cn",
        img: "https://cnevpost.com/wp-content/uploads/2026/09/2026091211442169.jpg",
        note: ""
    },
    // 2026-09-13 (google検索からExcel sheet2_llm_targets)
    {
        id: "cn3",
        title: "吉利EX5改良型、大型フランクと半格納ドアハンドルを確認",
        desc: "中国で9月21日発売予定の吉利EX5改良型は、新バンパー、半格納ドアハンドル、ルーフ上LiDARを採用し、充電口を前フェンダーから後部へ移す。公開写真のフロント収納には積載上限50kgと表示。正式な収納容量は未公表で、写真と申請情報に基づく発売前情報。",
        url: "https://carnewschina.com/2026/09/13/the-new-geely-ex5-reveals-a-huge-front-trunk-in-china-ahead-of-launch-in-sept/",
        source: "CarNewsChina - EV",
        date: "2026-09-13",
        tags: ["バンパー"],

        edition: "exterior", productScore: 80, exteriorScore: 80,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "The updated EX5 adopts new bumpers, semi-hidden door handles, and a roof-mounted LiDAR sensor.",
        interiorScore: 80,
        interiorReason: "具体部位の変更と開口・センサー配置が複数示される。フランク容量を写真から推定しない。",
        country: "cn",
        img: "https://carnewschina.com/wp-content/uploads/2026/09/geely_ex5_frunk-1500x844.jpg",
        note: ""
    },
    // 2026-09-14 (google検索からExcel sheet2_llm_targets)
    {
        id: "eu5",
        title: "VWのコンセプトMission Efficiency、後輪カバーと可動冷却部を採用",
        desc: "VWのコンセプト「Mission Efficiency」は、後輪を覆うカバー、前輪の整流板、必要時だけ開く冷却用フラップ、ほぼ全面を覆うアンダーボディを採用。Auto & Designは、絞り込んだ後部形状と併せて空力重視の設計を紹介した。",
        url: "https://autodesignmagazine.com/en/2026/09/volkswagen-mission-efficiency-aerodynamics-takes-the-lead/",
        source: "Auto & Design",
        date: "2026-09-14",
        tags: ["空力"],

        edition: "exterior", productScore: 90, exteriorScore: 90,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "A Cx of 0.158: this is the figure that makes the Mission",
        sourceExcerptEnd: "its shape is defined not by designers but by airflow.",
        interiorScore: 90,
        interiorReason: "後輪カバー、前輪整流板、可動冷却部、アンダーボディ、後端形状という複数の具体的な外装空力部品を説明。コンセプトの構造検討資料として適格。",
        country: "eu",
        img: "https://autodesignmagazine.com/wp-content/uploads/2026/09/VW-Mission-Efficiency_VW4_20260914_DB2026AU00677.jpg",
        note: ""
    },
    {
        id: "eu8",
        title: "キアPV7、張り出したホイールアーチと窓周りの輪郭を採用",
        desc: "キアは2027年後半の販売を予定するPV7を公開。乗員仕様を持つ全長5,350mmの電動バンで、張り出したホイールアーチや窓周りの輪郭を新たに設計した。Auto Expressは、ガラスルーフの選択肢や新しい車輪・外装色も紹介している。",
        url: "https://www.autoexpress.co.uk/kia/370424/new-kia-pv7-nine-seats-and-350kw-charging-pv5s-big-brother",
        source: "Auto Express",
        date: "2026-09-14",
        tags: [],

        edition: "exterior", productScore: 76, exteriorScore: 76,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "This is the new Kia PV7, big brother to the Auto Express",
        sourceExcerptEnd: "impressed us as both a family hauler and commercial workhorse.",
        interiorScore: 76,
        interiorReason: "Passenger仕様を含む車両のホイールアーチ、窓周り、ルーフ、車体形態の具体的な外装情報がある。電池・充電仕様だけの記事として扱わない。",
        country: "eu",
        img: "https://media.autoexpress.co.uk/image/private/s--X-WVjvBW--/f_auto,t_content-image-full-desktop@1/v1789130314/autoexpress/2026/09/Kia PV7 Passenger 2026.jpg",
        note: ""
    },
    {
        id: "eu9",
        title: "Leapmotor B03X、欧州で2万4,900ユーロから展開",
        desc: "Electric Cars Reportは、欧州で7月受注開始とするB03Xの試乗会と装備を紹介。全長4,270mm、開始価格2万4,900ユーロの小型EVで、前部LEDライトバー、格納式ドアハンドル、浮いたように見せるルーフ意匠を備える。",
        url: "https://electriccarsreport.com/2026/09/leapmotor-b03x-arrives-in-europe-with-e24900-starting-price/",
        source: "Electric Cars Report",
        date: "2026-09-14",
        tags: ["照明・発光"],

        edition: "exterior", productScore: 74, exteriorScore: 74,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "competitor",
        sourceExcerpt: "Leapmotor is expanding its presence in Europe with the new B03X, a",
        sourceExcerptEnd: "to combine SUV-inspired practicality, modern technology and an accessible price.",
        interiorScore: 74,
        interiorReason: "欧州向け小型EVの導入時期・価格・車体寸法と具体的な外装装備を提示。競合の価格帯と車体企画の比較に使える情報であり、販売成功や地域全体の需要は推定しない。",
        country: "eu",
        img: "https://electriccarsreport.com/wp-content/uploads/2026/09/Leapmotor-B03X.jpg",
        note: ""
    },
    // 2026-09-15 (google検索からExcel sheet2_llm_targets)
    {
        id: "jp8",
        title: "ノートBlack Edition、グリル・ミラー・エンブレムを黒で統一",
        desc: "くるまのニュースが、8月16日発売のノートBlack Editionを再紹介。フロントグリル、ドアミラー、ホイールカバー、正面エンブレムを黒で統一した仕様と、8月下旬に取材した販売店の反応を伝えている。",
        url: "https://news.yahoo.co.jp/articles/61a76735572cb27d5e77d0034fa34b50516bd69a?source=rss",
        source: "くるまのニュース",
        date: "2026-09-15",
        tags: ["グリル", "エンブレム"],

        edition: "exterior", productScore: 78, exteriorScore: 78,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "エクステリアでは、フロントグリルやドアミラー、ホイールカバーをはじめ、正面のブランドロゴエンブレムまでブラックで統一しています。",
        interiorScore: 78,
        interiorReason: "乗用車の複数外装部品を黒色で統一する加飾構成の具体例。個店の反応は全国需要と区別する。",
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-01109366-kurumans-000-1-view.jpg?exp=10800",
        note: ""
    },
    {
        id: "jp9",
        title: "エブリイとワゴン、用途別の前面意匠と新色を再紹介",
        desc: "ベストカーWebが2026年5月の改良を振り返った。エブリイは堅牢さ、乗用モデルのエブリイワゴンは力強さと上質感をテーマに前面意匠を変更。ワゴンには新色の濃灰色パールメタリックも設定したと紹介している。",
        url: "https://news.yahoo.co.jp/articles/6f97815390f76516b503380dbae1856fc33f3c46?source=rss",
        source: "ベストカーWeb",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 72, exteriorScore: 72,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "design",
        sourceExcerpt: "軽商用車の定番スズキ エブリイと、乗用モデルのエブリイワゴンが2026年5月に大幅改良を受けた。",
        interiorScore: 72,
        interiorReason: "同系車体の商用・乗用で異なる前面意匠テーマを使い分ける車種デザイン戦略。乗用ワゴンの企画検討に関係する。",
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-00000018-bestcar-000-1-view.jpg?exp=10800",
        note: ""
    },
    {
        id: "jp10",
        title: "ハイエース ワゴン、上半期販売は前年同期比約2.32倍と報道",
        desc: "carview!は、10人乗りのハイエース ワゴンの2026年上半期販売が前年同期比231.7％だったと紹介。一般的な7〜8人乗りミニバンと比較し、大人数と荷物を運べる車体構成への需要を論じた。特定外装部品の需要量を示す記事ではない。",
        url: "https://news.yahoo.co.jp/articles/34610226afd3b406b3e5c9e1ea2fa2c547d364c1?source=rss",
        source: "carview!",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 76, exteriorScore: 76,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "大家族での長距離旅行や、複数の家族が乗り合わせてのレジャー、あるいはスポーツチームの遠征など、人と荷物を同時に大量に運ぶ必要がある場面において、ハイエース ワゴンの実用性の高さは他のミニバンの追随を許さない。",
        interiorScore: 76,
        interiorReason: "乗用ワゴンの販売実績と多人数移動用途を扱う市場情報。231.7％は約2.32倍であり231.7％増ではない。",
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-00010007-carv-000-1-view.jpg?exp=10800",
        note: ""
    },
    {
        id: "jp11",
        title: "アルピーヌ×ラコステ、灯火やアンテナにブランドモチーフ",
        desc: "AUTOCAR JAPANは、フランスで披露された1台限定のA290ラリーを紹介。内外装計290のワニモチーフに加え、ヘッドライトを目、シャークフィンアンテナを背の突起に見立てた。量産車への採用発表ではなく、ブランド協業の意匠事例。",
        url: "https://news.yahoo.co.jp/articles/b5c45fc6c75b647979d3dc20795d7953690b0454?source=rss",
        source: "AUTOCAR JAPAN",
        date: "2026-09-15",
        tags: ["照明・発光"],

        edition: "exterior", productScore: 78, exteriorScore: 78,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "design",
        sourceExcerpt: "ボンネット上の『弁当箱』と呼ばれる窪みでは3匹のワニが泳ぎ、ヘッドライトはワニの眼差を思わせ、シャークフィンアンテナは背の突起へと姿を変えている。",
        interiorScore: 78,
        interiorReason: "外装部品の形状をブランドの図像へ結び付ける具体的なデザイン事例。日本媒体によるフランスのコンセプト車報道として記述する。",
        country: "jp",
        img: "https://newsatcl-pctr.c.yimg.jp/t/amd-img/20260915-01278165-autocar-000-1-view.jpg?exp=10800",
        note: ""
    },
    {
        id: "us4",
        title: "新型パジェロ、スペアタイヤを床下へ移し後部の使い勝手を改善",
        desc: "米Motor1は三菱の新型パジェロが背面スペアタイヤを床下へ移し、横開き式から一般的なテールゲートへ変更したと報道。荷室利用や牽引用品との干渉を改善し、後部には従来を想起させる六角形の意匠を残す。米国販売決定の報道ではない。",
        url: "https://www.motor1.com/news/808297/mitsubishi-pajero-why-lost-external-spare-wheel/",
        source: "Motor1",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 80, exteriorScore: 80,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "Mitsubishi claims the old setup made the rear door heavier and created practical headaches.",
        interiorScore: 80,
        interiorReason: "外装意匠と実使用の要求が具体的に結び付く。公開ページは今回403だが保存済みCSVに約4000字の元記事本文があり、本文で根拠確認。",
        country: "us",
        img: "https://cdn.motor1.com/images/mgl/jlWbjy/s3/2027-mitsubishi-pajero.jpg",
        note: ""
    },
    {
        id: "us5",
        title: "米カリフォルニアの灯火色規定を解説、前方は原則白・黄",
        desc: "Jalopnikは米カリフォルニア州の灯火色規定を解説した。現行Vehicle Code 25950では前方に見える灯火は原則白・黄で、後部側方マーカーや自動運転車のADSマーカー等は例外。発光加飾にも関わる既存規制の説明で、新たな禁止措置の発表ではない。",
        url: "https://www.jalopnik.com/2257345/why-california-bans-red-lights-front-of-cars/",
        source: "Jalopnik",
        date: "2026-09-15",
        tags: ["照明・発光", "外装加飾"],

        edition: "exterior", productScore: 76, exteriorScore: 76,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "regulation",
        sourceExcerpt: "However, one lesser-known area of regulation pertains to headlight color.",
        interiorScore: 76,
        interiorReason: "外装の発光色に直接関係する既存規制の解説。公式現行法条文も読み、記事だけでは抜ける例外と新設規制ではない点を補正。",
        country: "us",
        img: "https://www.jalopnik.com/img/gallery/why-california-bans-forward-facing-red-lights-on-cars/l-intro-1789393848.jpg",
        note: ""
    },
    {
        id: "eu6",
        title: "アウディNuvolari試乗、S字形吸気口と3設定の可動リア翼",
        desc: "Auto ExpressのAudi Nuvolari試乗記事は、S字形吸気口、格納・低荷重・高荷重の3設定を持つリアウイング、後部の大型排熱口を紹介。冷却や空力の効果は記事・メーカー説明で、比較試験の実測値は示されていない。",
        url: "https://www.autoexpress.co.uk/audi/370440/new-audi-nuvolari-review-stunning-ps500k-supercar-makes-r8-seem-slow",
        source: "Auto Express",
        date: "2026-09-15",
        tags: ["空力"],

        edition: "exterior", productScore: 85, exteriorScore: 85,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "\"The Nuvolari is Audi's first supercar with a high-performance hybrid drive, setting",
        sourceExcerptEnd: "its aerodynamics and the world-first quattro predictive ride,\" says Mohr.",
        interiorScore: 85,
        interiorReason: "S字形吸気口、可動リア翼の設定、後部排熱口、前後の空力部品など外装形状と機構の具体情報がある。試乗記として発売日と区別して扱う。",
        country: "eu",
        img: "https://media.autoexpress.co.uk/image/private/s--X-WVjvBW--/f_auto,t_content-image-full-desktop@1/v1789478002/autoexpress/2026/09/8a95b013-ed9e-43ec-b6b7-f921aa2708d3_HR_4c_yjfvn9.jpg",
        note: ""
    },
    {
        id: "eu10",
        title: "特注ファントム、2色の外板塗装とハチドリの装飾ラインを紹介",
        desc: "Auto Expressが特注Phantom Hummingbirdを紹介。車体上部をWildberry、下部をWhite Sandsに塗り分け、White Sandsの細い装飾ラインにハチドリの絵柄を組み込んだ。顧客の依頼による1台限りの仕様。",
        url: "https://www.autoexpress.co.uk/rolls-royce/phantom/370437/rolls-royce-phantom-hummingbird-one-worth-shelling-out",
        source: "Auto Express",
        date: "2026-09-15",
        tags: ["外装加飾"],

        edition: "exterior", productScore: 65, exteriorScore: 65,
        digestDate: "2026-09-15",
        contentCategory: "product", trendTopic: "",
        sourceExcerpt: "Moving to the outside, there’s a two-tone paint finish featuring Wildberry at the top and White Sands along the bottom.",
        interiorScore: 65,
        interiorReason: "記事の中心は内装の象嵌だが、外装の上下塗り分けとコーチラインへの絵柄統合が部位・色名付きで確認できる。外装加飾の独立事例として、その事実だけを掲載する。",
        country: "eu",
        img: "https://media.autoexpress.co.uk/image/private/s--X-WVjvBW--/f_auto,t_content-image-full-desktop@1/v1789469425/autoexpress/2026/09/Rolls-Royce Phantom Hummingbird-7.jpg",
        note: ""
    },
    {
        id: "in8",
        title: "BMWインド、LWB比率は上期52％、年末約60％を予想",
        desc: "BMW IndiaのCEOは、2026年上期に販売の52％を占めたロングホイールベース車が年末には約60％に達すると見込む。後席空間を重視する製品方針を示した発言で、対象はBMWのインド販売。年末の数値は予測である。",
        url: "https://www.autocarindia.com/car-news/lwb-models-could-make-up-60-percent-of-sales-by-year-end-bmw-india-ceo-440747",
        source: "Autocar India - All",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 78, exteriorScore: 78,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "“Long wheelbase and electrification are the two pillars we are working on",
        sourceExcerptEnd: "the sidelines of the launch of the BMW i5 LWB.",
        interiorScore: 78,
        interiorReason: "対象メーカー・地域・期間が明確な車体タイプ別販売比率とCEOの見通し。ホイールベースや乗員空間を含む車体企画の条件を検討する市場情報。外装部品需要増の直接根拠ではない。",
        country: "in",
        img: "https://asset.autocarindia.com/static/news/images/20260915_110722_11cf11ae.jpeg",
        note: ""
    },
    {
        id: "in9",
        title: "インド8月販売、上位10車種は18.3万台で前年比33％増",
        desc: "Autocar Indiaによると、2026年8月のインド販売上位10車種は計18万3,037台で前年比33％増。Tata Punchが2万1,320台で首位となった。記事は、前年同月の税制変更待ちによる購入延期と出荷抑制で比較基準が低かった点も挙げる。",
        url: "https://www.autocarindia.com/car-news/top-10-bestselling-cars-in-august-2026-punch-back-on-top-spot-440753",
        source: "Autocar India - All",
        date: "2026-09-15",
        tags: [],

        edition: "exterior", productScore: 79, exteriorScore: 79,
        digestDate: "2026-09-15",
        contentCategory: "trend", trendTopic: "market",
        sourceExcerpt: "The Tata Punch was India’s bestselling car in August 2026, with 21,320 units sold, ahead of the Maruti Suzuki Wagon R and Swift.",
        interiorScore: 79,
        interiorReason: "月・地域・車種別の販売台数、比較年、前年比増加の背景が具体的。企画対象車種と数量規模の参考になるが、外装意匠が販売増の原因とは推定しない。",
        country: "in",
        img: "https://asset.autocarindia.com/static/news/images/20260915_102600_60ed4ae1.jpeg",
        note: ""
    },
];
